import { Injectable } from '@angular/core';

export class ProductsService {

  constructor() { }

  items = [{
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s8-active.jpg',
    name: 'Samsung Galaxy S8 Active',
    size: '208.1g, 9.9mm thickness',
    os: 'Android 7.0',
    storage: '64GB storage, microSD card slot',
    displaySize: '5.8"',
    cameraSize: '12MP',
    memory: '4GB RAM',
    chipset: 'Snapdragon 835',
    batteryMaH: '4000mAh',
    price: 'About 850 USD',
    id: 1
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-j7-max.jpg',
    name: 'Samsung Galaxy J7 Max',
    size: '179g, 8.1mm thickness',
    os: 'Android 7.0',
    storage: '32GB storage, microSD card slot',
    displaySize: '5.7"',
    cameraSize: '13MP',
    memory: '4GB RAM',
    chipset: 'MT6757 Helio P20',
    batteryMaH: '3300mAh',
    price: 'About 250 EUR',
    id: 2
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-z4.jpg',
    name: 'Samsung Z4',
    size: '143g, 10.3mm thickness',
    os: 'Tizen 3.0',
    storage: '8GB storage, microSD card slot',
    displaySize: '4.5"',
    cameraSize: '5MP',
    memory: '1GB RAM',
    chipset: '',
    batteryMaH: '2050mAh',
    price: 'About 300 EUR',
    id: 3
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-j7-v-2017.jpg',
    name: 'Samsung Galaxy J7 V',
    size: '167.3g, 8.6mm thickness',
    os: 'Android 7.0.1',
    storage: '16GB storage, microSD card slot',
    displaySize: '5.5"',
    cameraSize: '8MP',
    memory: '2GB RAM',
    chipset: 'Snapdragon 625',
    batteryMaH: '3300mAh',
    price: 'About 240 USD',
    id: 4
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-j5-2017-sm-j530.jpg',
    name: 'Samsung Galaxy J5 (2017)',
    size: '160g, 8mm thickness',
    os: 'Android 7.0',
    storage: '16GB storage, microSD card slot',
    displaySize: '5.2"',
    cameraSize: '13MP',
    memory: '3GB RAM',
    chipset: 'Exynos 7870 Octa',
    batteryMaH: '3000mAh',
    price: 'About 300 EUR',
    id: 6
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-note-fe.jpg',
    name: 'Samsung Galaxy Note FE',
    size: '167g, 7.9mm thickness',
    os: 'Android 7.1.1',
    storage: '64GB storage, microSD card slot',
    displaySize: '5.7"',
    cameraSize: '12MP',
    memory: '4GB RAM',
    chipset: 'Exynos 8890 Octa',
    batteryMaH: '3200mAh',
    price: 'About 540 EUR',
    id: 7
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-j3-2017.jpg',
    name: 'Samsung Galaxy J3 (2017)',
    size: '142g, 8.2mm thickness',
    os: 'Android 7.0',
    storage: '16GB storage, microSD card slot',
    displaySize: '5.0"',
    cameraSize: '13MP',
    memory: '2GB RAM',
    chipset: 'Exynos 7570 Quad',
    batteryMaH: '2400mAh',
    price: 'About 220 EUR',
    id: 8
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-note8-r.jpg',
    name: 'Samsung Galaxy Note8',
    size: '195g, 8.6mm thickness',
    os: 'Android 7.1.1',
    storage: '64/128/256GB storage, microSD card slot',
    displaySize: '6.3"',
    cameraSize: '12MP',
    memory: '6GB RAM',
    chipset: 'Exynos 8895 Octa',
    batteryMaH: '3300mAh',
    price: 'About 1000 EUR',
    id: 9
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-j7-2017-sm-j730f.jpg',
    name: 'Samsung Galaxy J7 (2017)',
    size: '181g, 8mm thickness',
    os: 'Android 7.0',
    storage: '16GB storage, microSD card slot',
    displaySize: '5.5"',
    cameraSize: '13MP',
    memory: '3GB RAM',
    chipset: 'Exynos 7870 Octa',
    batteryMaH: '3600mAh',
    price: 'About 300 EUR',
    id: 10
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-gear-sport1.jpg',
    name: 'Samsung Gear Sport',
    size: '67g (w/ strap); 50g (w/о strap), 11.6mm thickness',
    os: 'Tizen-based wearable platform 3.0',
    storage: '4GB storage, no card slot',
    displaySize: '1.2"',
    cameraSize: 'NO',
    memory: '768MB RAM',
    chipset: 'Exynos 3250 Dual',
    batteryMaH: '300mAh',
    price: 'About 220 EUR',
    id: 11
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-gear-s3-classic-lte.jpg',
    name: 'Samsung Gear S3 classic LTE',
    size: '57g, 12.9mm thickness',
    os: 'Tizen-based wearable platform 2.3.2',
    storage: '4GB storage, no card slot',
    displaySize: '1.3"',
    cameraSize: 'NO',
    memory: '768MB RAM',
    chipset: 'Exynos 7270',
    batteryMaH: '380mAh',
    price: 'About 300 EUR',
    id: 12
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-xcover4-g390f-.jpg',
    name: 'Samsung Galaxy Xcover 4',
    size: '172g, 9.7mm thickness',
    os: 'Android 7.0',
    storage: '16GB storage, microSD card slot',
    displaySize: '5.0"',
    cameraSize: '13MP',
    memory: '2GB RAM',
    chipset: 'Exynos 7570 Quad',
    batteryMaH: '2800mAh',
    price: 'About 240 EUR',
    id: 13
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-j1-nxt.jpg',
    name: 'Samsung Galaxy J1 mini prime',
    size: '126g, 10.8mm thickness',
    os: 'Android 5.1 - 3G modelAndroid…',
    storage: '8GB storage, microSD card slot',
    displaySize: '4.0"',
    cameraSize: '5MP',
    memory: '1GB RAM',
    chipset: 'Spreadtrum SC9830',
    batteryMaH: '1500mAh',
    price: 'About 110 EUR',
    id: 14
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-tab-s3-97-sm-t825.jpg',
    name: 'Samsung Galaxy Tab S3 9.7',
    size: '429g (Wi-Fi)/ 434g (LTE), 6mm thickness',
    os: 'Android 7.0',
    storage: '32GB storage, microSD card slot',
    displaySize: '9.7"',
    cameraSize: '13MP',
    memory: '4GB RAM',
    chipset: 'Snapdragon 820',
    batteryMaH: '6000mAh',
    price: 'About 750 EUR',
    id: 15
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-j7-2016.jpg',
    name: 'Samsung Galaxy On8',
    size: '169g, 7.8mm thickness',
    os: 'Android 6.0.1',
    storage: '16GB storage, microSD card slot',
    displaySize: '5.5"',
    cameraSize: '13MP',
    memory: '3GB RAM',
    chipset: 'Exynos 7580 Octa',
    batteryMaH: '3300mAh',
    price: 'About 300 EUR',
    id: 16
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-gear-s3-classic.jpg',
    name: 'Samsung Gear S3 classic',
    size: '59g, 12.9mm thickness',
    os: 'Tizen-based wearable platform 2.3.2',
    storage: '4GB storage, no card slot',
    displaySize: '1.3"',
    cameraSize: 'NO',
    memory: '768MB RAM',
    chipset: 'Exynos 7270',
    batteryMaH: '380mAh',
    price: 'About 390 EUR',
    id: 17
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a3-2017.jpg',
    name: 'Samsung Galaxy A3 (2017)',
    size: '138g, 7.9mm thickness',
    os: 'Android 6.0.1, up to 7.0',
    storage: '16GB storage, microSD card slot',
    displaySize: '4.7"',
    cameraSize: '13MP',
    memory: '2GB RAM',
    chipset: 'Exynos 7870 Octa',
    batteryMaH: '2350mAh',
    price: 'About 300 EUR',
    id: 18
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-j2-prime-2016.jpg',
    name: 'Samsung Galaxy Grand Prime Plus',
    size: '160g, 8.9mm thickness',
    os: 'Android 6.0',
    storage: '8GB storage, microSD card slot',
    displaySize: '5.0"',
    cameraSize: '8MP',
    memory: '1.5GB RAM',
    chipset: 'MT6737T',
    batteryMaH: '2600mAh',
    price: 'About 140 EUR',
    id: 19
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-on7-2016-g6100-c.jpg',
    name: 'Samsung Galaxy On7 (2016)',
    size: '167g, 8mm thickness',
    os: 'Android 6.0.1',
    storage: '32GB storage, microSD card slot',
    displaySize: '5.5"',
    cameraSize: '13MP',
    memory: '3GB RAM',
    chipset: 'Snapdragon 625',
    batteryMaH: '3300mAh',
    price: 'About 260 EUR',
    id: 20
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-gear-s3-frontier-lte.jpg',
    name: 'Samsung Gear S3 frontier LTE',
    size: '63g, 12.9mm thickness',
    os: 'Tizen-based wearable platform 2.3.2',
    storage: '4GB storage, no card slot',
    displaySize: '1.3"',
    cameraSize: 'NO',
    memory: '768MB RAM',
    chipset: 'Exynos 7270',
    batteryMaH: '380mAh',
    price: 'About 450 EUR',
    id: 21
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-tab-a-101-2016.jpg',
    name: 'Samsung Galaxy Tab A 10.1 (2016)',
    size: '525g, 8.2mm thickness',
    os: 'Android 6.0, up to 7.0',
    storage: '16GB storage, microSD card slot',
    displaySize: '10.1"',
    cameraSize: '8MP',
    memory: '2GB RAM',
    chipset: 'Exynos 7870',
    batteryMaH: '7300mAh',
    price: 'About 220 EUR',
    id: 22
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-z3.jpg',
    name: 'Samsung Z3 Corporate Edition',
    size: '7.9mm thickness',
    os: 'Tizen 2.4',
    storage: '8GB storage, microSD card slot',
    displaySize: '5.0"',
    cameraSize: '8MP',
    memory: '1GB RAM',
    chipset: 'Snapdragon 410',
    batteryMaH: '2600mAh',
    price: 'About 270 EUR',
    id: 23
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-c5-pro-sm-c5010.jpg',
    name: 'Samsung Galaxy C5 Pro',
    size: '145g, 7mm thickness',
    os: 'Android 7.0',
    storage: '64GB storage, microSD card slot',
    displaySize: '5.2"',
    cameraSize: '16MP',
    memory: '4GB RAM',
    chipset: 'Snapdragon 626',
    batteryMaH: '2600mAh',
    price: 'About 300 EUR',
    id: 24
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-c7-pro.jpg',
    name: 'Samsung Galaxy C7 Pro',
    size: '172g, 7mm thickness',
    os: 'Android 6.0.1',
    storage: '64GB storage, microSD card slot',
    displaySize: '5.7"',
    cameraSize: '16MP',
    memory: '4GB RAM',
    chipset: 'Snapdragon 626',
    batteryMaH: '3300mAh',
    price: 'About 420 EUR',
    id: 25
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-j5-prime.jpg',
    name: 'Samsung Galaxy J5 Prime',
    size: '143g, 8.1mm thickness',
    os: 'Android 6.0.1',
    storage: '16/32GB storage, microSD card slot',
    displaySize: '5.0"',
    cameraSize: '13MP',
    memory: '2GB RAM',
    chipset: 'Exynos 7570 Quad',
    batteryMaH: '2400mAh',
    price: 'About 230 EUR',
    id: 26
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-j2-prime-2016.jpg',
    name: 'Samsung Galaxy J2 Prime',
    size: '160g, 8.9mm thickness',
    os: 'Android 6.0',
    storage: '8GB storage, microSD card slot',
    displaySize: '5.0"',
    cameraSize: '8MP',
    memory: '1.5GB RAM',
    chipset: 'MT6737T',
    batteryMaH: '2600mAh',
    price: 'About 300 EUR',
    id: 27
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a7-2017.jpg',
    name: 'Samsung Galaxy A7 (2017)',
    size: '186g, 7.9mm thickness',
    os: 'Android 6.0.1, up to 7.0',
    storage: '32GB storage, microSD card slot',
    displaySize: '5.7"',
    cameraSize: '16MP',
    memory: '3GB RAM',
    chipset: 'Exynos 7880 Octa',
    batteryMaH: '3600mAh',
    price: 'About 300 EUR',
    id: 28
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-j-tablet1.jpg',
    name: 'Samsung Galaxy Tab J',
    size: '289g, 8.7mm thickness',
    os: 'Android 5.1',
    storage: '8GB storage, microSD card slot',
    displaySize: '7.0"',
    cameraSize: '8MP',
    memory: '1.5GB RAM',
    chipset: 'Spreadtrum SC8830',
    batteryMaH: '4000mAh',
    price: 'About 300 EUR',
    id: 29
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a9-pro1.jpg',
    name: 'Samsung Galaxy A9 (2016)',
    size: '200g, 7.4mm thickness',
    os: 'Android 5.1.1, up to 6.0.1',
    storage: '32GB storage, microSD card slot',
    displaySize: '6.0"',
    cameraSize: '13MP',
    memory: '3GB RAM',
    chipset: 'Snapdragon 652',
    batteryMaH: '4000mAh',
    price: 'About 300 EUR',
    id: 30
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-j3-emerge-.jpg',
    name: 'Samsung Galaxy J3 Emerge',
    size: '147g, 8.7mm thickness',
    os: 'Android 6.0.1Android 7.0 - Am…',
    storage: '16GB storage, microSD card slot',
    displaySize: '5.0"',
    cameraSize: '5MP',
    memory: '1.5GB RAM',
    chipset: 'Snapdragon 430',
    batteryMaH: '2600mAh',
    price: 'About 235 USD',
    id: 31
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-xcover-3-SM-G389F.jpg',
    name: 'Samsung Galaxy Xcover 3 G389F',
    size: '154g, 10mm thickness',
    os: 'Android 6.0',
    storage: '8GB storage, microSD card slot',
    displaySize: '4.5"',
    cameraSize: '5MP',
    memory: '1.5GB RAM',
    chipset: 'Exynos 3475 Quad',
    batteryMaH: '2200mAh',
    price: 'About 300 EUR',
    id: 32
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-note7.jpg',
    name: 'Samsung Galaxy Note7',
    size: '169g, 7.9mm thickness',
    os: 'Android 6.0.1',
    storage: '64GB storage, microSD card slot',
    displaySize: '5.7"',
    cameraSize: '12MP',
    memory: '4GB RAM',
    chipset: 'Exynos 8890 Octa',
    batteryMaH: '3500mAh',
    price: 'About 300 EUR',
    id: 33
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-z3.jpg',
    name: 'Samsung Z3',
    size: '137g, 7.9mm thickness',
    os: 'Tizen 2.3, up to 2.4',
    storage: '8GB storage, microSD card slot',
    displaySize: '5.0"',
    cameraSize: '8MP',
    memory: '1GB RAM',
    chipset: 'Spreadtrum SC7730',
    batteryMaH: '2600mAh',
    price: 'About 110 EUR',
    id: 34
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a5-2017-new.jpg',
    name: 'Samsung Galaxy A5 (2017)',
    size: '157g, 7.9mm thickness',
    os: 'Android 6.0.1, up to 7.0',
    storage: '32GB storage, microSD card slot',
    displaySize: '5.2"',
    cameraSize: '16MP',
    memory: '3GB RAM',
    chipset: 'Exynos 7880 Octa',
    batteryMaH: '3000mAh',
    price: 'About 300 EUR',
    id: 35
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-j7-prime.jpg',
    name: 'Samsung Galaxy J7 Prime',
    size: '167g, 8mm thickness',
    os: 'Android 6.0.1',
    storage: '16/32GB storage, microSD card slot',
    displaySize: '5.5"',
    cameraSize: '13MP',
    memory: '3GB RAM',
    chipset: 'Exynos 7870 Octa',
    batteryMaH: '3300mAh',
    price: 'About 280 EUR',
    id: 36
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-c9-pro-.jpg',
    name: 'Samsung Galaxy C9 Pro',
    size: '189g, 6.9mm thickness',
    os: 'Android 6.0.1',
    storage: '64GB storage, microSD card slot',
    displaySize: '6.0"',
    cameraSize: '16MP',
    memory: '6GB RAM',
    chipset: 'Snapdragon 653',
    batteryMaH: '4000mAh',
    price: 'About 620 EUR',
    id: 37
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a3-2016.jpg',
    name: 'Samsung Galaxy A3 (2016)',
    size: '132g, 7.3mm thickness',
    os: 'Android 5.1.1, up to 7.0',
    storage: '16GB storage, microSD card slot',
    displaySize: '4.7"',
    cameraSize: '13MP',
    memory: '1.5GB RAM',
    chipset: 'Exynos 7578',
    batteryMaH: '2300mAh',
    price: 'About 200 EUR',
    id: 38
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-express-prime.jpg',
    name: 'Samsung Galaxy Express Prime',
    size: '138.9g, 7.9mm thickness',
    os: 'Android 6.0',
    storage: '16GB 1.5GB RAM storage, microSD card slot',
    displaySize: '5.0"',
    cameraSize: '5MP',
    memory: '1.5GB RAM',
    chipset: 'Exynos 3475 Quad',
    batteryMaH: '2600mAh',
    price: 'About 110 EUR',
    id: 39
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-gear-s2-classic-3g.jpg',
    name: 'Samsung Gear S2 classic 3G',
    size: '54g, 13.4mm thickness',
    os: 'Tizen-based wearable platform',
    storage: '4GB storage, no card slot',
    displaySize: '1.2"',
    cameraSize: 'NO',
    memory: '512MB RAM',
    chipset: 'Exynos 3250 Dual',
    batteryMaH: '300mAh',
    price: 'About 350 EUR',
    id: 40
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s6-edge-plus.jpg',
    name: 'Samsung Galaxy S6 edge+ Duos',
    size: '153g, 6.9mm thickness',
    os: 'Android 5.1.1, up to 6.0.1',
    storage: '32/64GB storage, no card slot',
    displaySize: '5.7"',
    cameraSize: '16MP',
    memory: '4GB RAM',
    chipset: 'Exynos 7420 Octa',
    batteryMaH: '3000mAh',
    price: 'About 530 EUR',
    id: 41
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-j1-nxt.jpg',
    name: 'Samsung Galaxy J1 Nxt',
    size: '123g, 10.8mm thickness',
    os: 'Android 5.1',
    storage: '8GB storage, microSD card slot',
    displaySize: '4.0"',
    cameraSize: '5MP',
    memory: '1GB RAM',
    chipset: 'Spreadtrum SC9830',
    batteryMaH: '1500mAh',
    price: 'About 90 EUR',
    id: 42
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s8-.jpg',
    name: 'Samsung Galaxy S8',
    size: '155g, 8mm thickness',
    os: 'Android 7.0',
    storage: '64GB storage, microSD card slot',
    displaySize: '5.8"',
    cameraSize: '12MP',
    memory: '4GB RAM',
    chipset: 'Exynos 8895 Octa',
    batteryMaH: '3000mAh',
    price: 'About 300 EUR',
    id: 43
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s8-plus-.jpg',
    name: 'Samsung Galaxy S8+',
    size: '173g, 8.1mm thickness',
    os: 'Android 7.0',
    storage: '64GB storage, microSD card slot',
    displaySize: '6.2"',
    cameraSize: '12MP',
    memory: '6GB RAM',
    chipset: 'Exynos 8895 Octa',
    batteryMaH: '3500mAh',
    price: 'About 300 EUR',
    id: 44
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-gear-s2.jpg',
    name: 'Samsung Gear S2 3G',
    size: '51g, 13.4mm thickness',
    os: 'Tizen-based wearable platform',
    storage: '4GB storage, no card slot',
    displaySize: '1.2"',
    cameraSize: 'NO',
    memory: '512MB RAM',
    chipset: 'MSM8x26',
    batteryMaH: '300mAh',
    price: 'About 300 EUR',
    id: 45
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-view.jpg',
    name: 'Samsung Galaxy View',
    size: '2.65 kg, 11.9mm thickness',
    os: 'Android 5.1.1',
    storage: '32/64GB storage, microSD card slot',
    displaySize: '18.4"',
    cameraSize: '2.1MP',
    memory: '2GB RAM',
    chipset: 'Exynos 7580 Octa',
    batteryMaH: '5700mAh',
    price: 'About 640 EUR',
    id: 46
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a7-2016.jpg',
    name: 'Samsung Galaxy A7 (2016)',
    size: '172g, 7.3mm thickness',
    os: 'Android 5.1.1, up to 7.0',
    storage: '16GB storage, microSD card slot',
    displaySize: '5.5"',
    cameraSize: '13MP',
    memory: '3GB RAM',
    chipset: 'Exynos 7580 Octa',
    batteryMaH: '3300mAh',
    price: 'About 300 EUR',
    id: 47
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-j2-2016-new.jpg',
    name: 'Samsung Galaxy J2 Pro (2016)',
    size: '138g, 8mm thickness',
    os: 'Android 6.0.1',
    storage: '16GB storage, microSD card slot',
    displaySize: '5.0"',
    cameraSize: '8MP',
    memory: '2GB RAM',
    chipset: 'Spreadtrum SC8830',
    batteryMaH: '2600mAh',
    price: 'About 160 EUR',
    id: 48
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-tab-e-80.jpg',
    name: 'Samsung Galaxy Tab E 8.0',
    size: '360g, 8.9mm thickness',
    os: 'Android 5.1.1, up to 6.0',
    storage: '16GB storage, microSD card slot',
    displaySize: '8.0"',
    cameraSize: '5MP',
    memory: '1.5GB RAM',
    chipset: 'Snapdragon 410',
    batteryMaH: '5000mAh',
    price: 'About 180 EUR',
    id: 49
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a8-2016r1-.jpg',
    name: 'Samsung Galaxy A8 (2016)',
    size: '182g, 7.2mm thickness',
    os: 'Android 6.0.1',
    storage: '32GB storage, microSD card slot',
    displaySize: '5.7"',
    cameraSize: '16MP',
    memory: '3GB RAM',
    chipset: 'Exynos 7420 Octa',
    batteryMaH: '3300mAh',
    price: 'About 560 EUR',
    id: 50
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-tab-a-70-2016-.jpg',
    name: 'Samsung Galaxy Tab A 7.0 (2016)',
    size: '283g, 8.7mm thickness',
    os: 'Android 5.1.1',
    storage: '8GB storage, microSD card slot',
    displaySize: '7.0"',
    cameraSize: '5MP',
    memory: '1.5GB RAM',
    chipset: 'Snapdragon 410',
    batteryMaH: '4000mAh',
    price: 'About 130 EUR',
    id: 51
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-folder-SM-G150.jpg',
    name: 'Samsung Galaxy Folder',
    size: '155g, 15.3mm thickness',
    os: 'Android 5.1',
    storage: '8GB storage, microSD card slot',
    displaySize: '3.8"',
    cameraSize: '8MP',
    memory: '1.5GB RAM',
    chipset: '',
    batteryMaH: '1800mAh',
    price: 'About 260 EUR',
    id: 52
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-on5.jpg',
    name: 'Samsung Galaxy On5 Pro',
    size: '149g, 8.5mm thickness',
    os: 'Android 6.0',
    storage: '16GB storage, microSD card slot',
    displaySize: '5.0"',
    cameraSize: '8MP',
    memory: '2GB RAM',
    chipset: 'Exynos 3475 Quad',
    batteryMaH: '2600mAh',
    price: 'About 150 EUR',
    id: 53
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-j7-2016.jpg',
    name: 'Samsung Galaxy J7 (2016)',
    size: '170g, 7.8mm thickness',
    os: 'Android 6.0.1',
    storage: '16GB storage, microSD card slot',
    displaySize: '5.5"',
    cameraSize: '13MP',
    memory: '2GB RAM',
    chipset: 'Snapdragon 617',
    batteryMaH: '3300mAh',
    price: 'About 300 EUR',
    id: 54
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-j5-2016r.jpg',
    name: 'Samsung Galaxy J5 (2016)',
    size: '159g, 8.1mm thickness',
    os: 'Android 6.0.1',
    storage: '16GB storage, microSD card slot',
    displaySize: '5.2"',
    cameraSize: '13MP',
    memory: '2GB RAM',
    chipset: 'Snapdragon 410',
    batteryMaH: '3100mAh',
    price: 'About 300 EUR',
    id: 55
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-c5r3.jpg',
    name: 'Samsung Galaxy C5',
    size: '143g, 6.7mm thickness',
    os: 'Android 6.0.1',
    storage: '32/64GB storage, microSD card slot',
    displaySize: '5.2"',
    cameraSize: '16MP',
    memory: '4GB RAM',
    chipset: 'Snapdragon 617',
    batteryMaH: '2600mAh',
    price: 'About 300 EUR',
    id: 57
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-z2.jpg',
    name: 'Samsung Z2',
    size: '127g, 10.8mm thickness',
    os: 'Tizen 2.4',
    storage: '8GB storage, microSD card slot',
    displaySize: '4.0"',
    cameraSize: '5MP',
    memory: '1GB RAM',
    chipset: 'Spreadtrum SC9830',
    batteryMaH: '1500mAh',
    price: 'About 80 EUR',
    id: 58
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-j-max3.jpg',
    name: 'Samsung Galaxy J Max',
    size: '289g, 8.7mm thickness',
    os: 'Android 5.1',
    storage: '8GB storage, microSD card slot',
    displaySize: '7.0"',
    cameraSize: '8MP',
    memory: '1.5GB RAM',
    chipset: 'Spreadtrum SC8830',
    batteryMaH: '4000mAh',
    price: 'About 220 EUR',
    id: 59
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-j1-2016.jpg',
    name: 'Samsung Galaxy J1 (2016)',
    size: '131g, 8.9mm thickness',
    os: 'Android 5.1.1',
    storage: '8GB storage, microSD card slot',
    displaySize: '4.5"',
    cameraSize: '5MP',
    memory: '1GB RAM',
    chipset: 'Spreadtrum SC9830',
    batteryMaH: '2050mAh',
    price: 'About 130 EUR',
    id: 60
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a5-2016.jpg',
    name: 'Samsung Galaxy A5 (2016)',
    size: '155g, 7.3mm thickness',
    os: 'Android 5.1.1, up to 7.0',
    storage: '16GB storage, microSD card slot',
    displaySize: '5.2"',
    cameraSize: '13MP',
    memory: '2GB RAM',
    chipset: 'Exynos 7580 Octa',
    batteryMaH: '2900mAh',
    price: 'About 300 EUR',
    id: 61
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s6-edge-plus.jpg',
    name: 'Samsung Galaxy S6 edge+',
    size: '153g, 6.9mm thickness',
    os: 'Android 5.1.1, up to 7.0',
    storage: '32/64GB storage, no card slot',
    displaySize: '5.7"',
    cameraSize: '16MP',
    memory: '4GB RAM',
    chipset: 'Exynos 7420 Octa',
    batteryMaH: '3000mAh',
    price: 'About 300 EUR',
    id: 62
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-gear-s3-frontier-lte.jpg',
    name: 'Samsung Gear S3 frontier',
    size: '63g, 12.9mm thickness',
    os: 'Tizen-based wearable platform 2.3.2',
    storage: '4GB storage, no card slot',
    displaySize: '1.3"',
    cameraSize: 'NO',
    memory: '768MB RAM',
    chipset: 'Exynos 7270',
    batteryMaH: '380mAh',
    price: 'About 350 EUR',
    id: 63
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s7--.jpg',
    name: 'Samsung Galaxy S7',
    size: '152g, 7.9mm thickness',
    os: 'Android 6.0, up to 7.0',
    storage: '32/64GB storage, microSD card slot',
    displaySize: '5.1"',
    cameraSize: '12MP',
    memory: '4GB RAM',
    chipset: 'Exynos 8890 Octa',
    batteryMaH: '3000mAh',
    price: 'About 300 EUR',
    id: 64
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s7-usa.jpg',
    name: 'Samsung Galaxy S7 (USA)',
    size: '152g, 7.9mm thickness',
    os: 'Android 6.0, up to 7.0',
    storage: '32GB storage, microSD card slot',
    displaySize: '5.1"',
    cameraSize: '12MP',
    memory: '4GB RAM',
    chipset: 'Snapdragon 820',
    batteryMaH: '3000mAh',
    price: 'About 450 EUR',
    id: 65
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-on5.jpg',
    name: 'Samsung Galaxy On5',
    size: '149g, 8.5mm thickness',
    os: 'Android 5.1Android 6.0 - T-Mo…',
    storage: '8GB storage, microSD card slot',
    displaySize: '5.0"',
    cameraSize: '8MP',
    memory: '1.5GB RAM',
    chipset: 'Exynos 3475 Quad',
    batteryMaH: '2600mAh',
    price: 'About 140 EUR',
    id: 67
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-gear-s2-classic.jpg',
    name: 'Samsung Gear S2 classic',
    size: '42g, 11.4mm thickness',
    os: 'Tizen-based wearable platform',
    storage: '4GB storage, no card slot',
    displaySize: '1.2"',
    cameraSize: 'NO',
    memory: '512MB RAM',
    chipset: 'Exynos 3250 Dual',
    batteryMaH: '250mAh',
    price: 'About 270 EUR',
    id: 68
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-note5.jpg',
    name: 'Samsung Galaxy Note5 (USA)',
    size: '171g, 7.6mm thickness',
    os: 'Android 5.1.1, up to 7.0',
    storage: '32/64GB storage, no card slot',
    displaySize: '5.7"',
    cameraSize: '16MP',
    memory: '4GB RAM',
    chipset: 'Exynos 7420 Octa',
    batteryMaH: '3000mAh',
    price: 'About 540 EUR',
    id: 69
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-on7-.jpg',
    name: 'Samsung Galaxy On7',
    size: '172g, 8.2mm thickness',
    os: 'Android 5.1, up to 6.0.1',
    storage: '8GB storage, microSD card slot',
    displaySize: '5.5"',
    cameraSize: '13MP',
    memory: '1.5GB RAM',
    chipset: 'Snapdragon 410',
    batteryMaH: '3000mAh',
    price: 'About 180 EUR',
    id: 70
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s6-edge-plus.jpg',
    name: 'Samsung Galaxy S6 edge+ (USA)',
    size: '153g, 6.9mm thickness',
    os: 'Android 5.1.1',
    storage: '32/64GB storage, no card slot',
    displaySize: '5.7"',
    cameraSize: '16MP',
    memory: '4GB RAM',
    chipset: 'Exynos 7420 Octa',
    batteryMaH: '3000mAh',
    price: 'About 550 EUR',
    id: 71
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s5-neo.jpg',
    name: 'Samsung Galaxy S5 Neo',
    size: '145g, 8.1mm thickness',
    os: 'Android 5.1.1, up to 7.0',
    storage: '16GB storage, microSD card slot',
    displaySize: '5.1"',
    cameraSize: '16MP',
    memory: '2GB RAM',
    chipset: 'Exynos 7580 Octa',
    batteryMaH: '2800mAh',
    price: 'About 350 EUR',
    id: 72
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s4-mini-plus-gt-i9195i.jpg',
    name: 'Samsung Galaxy S4 mini I9195I',
    size: '107g, 8.9mm thickness',
    os: 'Android 4.4.4',
    storage: '8GB storage, microSD card slot',
    displaySize: '4.3"',
    cameraSize: '8MP',
    memory: '1.5GB RAM',
    chipset: 'Snapdragon 410',
    batteryMaH: '1900mAh',
    price: 'About 190 EUR',
    id: 73
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-note5.jpg',
    name: 'Samsung Galaxy Note5',
    size: '171g, 7.6mm thickness',
    os: 'Android 5.1.1, up to 7.0',
    storage: '32/64/128GB storage, no card slot',
    displaySize: '5.7"',
    cameraSize: '16MP',
    memory: '4GB RAM',
    chipset: 'Exynos 7420 Octa',
    batteryMaH: '3000mAh',
    price: 'About 300 EUR',
    id: 74
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-j3-2017r1.jpg',
    name: 'Samsung Galaxy J3 Pro',
    size: '139g, 8mm thickness',
    os: 'Android 5.1',
    storage: '16GB storage, microSD card slot',
    displaySize: '5.0"',
    cameraSize: '8MP',
    memory: '2GB RAM',
    chipset: 'Snapdragon 410',
    batteryMaH: '2600mAh',
    price: 'About 150 EUR',
    id: 75
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-on7-.jpg',
    name: 'Samsung Galaxy On7 Pro',
    size: '172g, 8mm thickness',
    os: 'Android 6.0.1',
    storage: '16GB storage, microSD card slot',
    displaySize: '5.5"',
    cameraSize: '13MP',
    memory: '2GB RAM',
    chipset: 'Snapdragon 410',
    batteryMaH: '3000mAh',
    price: 'About 180 EUR',
    id: 76
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-c7.jpg',
    name: 'Samsung Galaxy C7',
    size: '169g, 6.8mm thickness',
    os: 'Android 6.0.1',
    storage: '32/64GB storage, microSD card slot',
    displaySize: '5.7"',
    cameraSize: '16MP',
    memory: '4GB RAM',
    chipset: 'Snapdragon 625',
    batteryMaH: '3300mAh',
    price: 'About 300 EUR',
    id: 77
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-note7-usa.jpg',
    name: 'Samsung Galaxy Note7 (USA)',
    size: '169g, 7.9mm thickness',
    os: 'Android 6.0.1',
    storage: '64GB storage, microSD card slot',
    displaySize: '5.7"',
    cameraSize: '12MP',
    memory: '4GB RAM',
    chipset: 'Snapdragon 820',
    batteryMaH: '3500mAh',
    price: 'About 300 EUR',
    id: 78
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s7-active.jpg',
    name: 'Samsung Galaxy S7 active',
    size: '184.8g, 9.9mm thickness',
    os: 'Android 6.0, up to 7.0',
    storage: '32GB storage, microSD card slot',
    displaySize: '5.1"',
    cameraSize: '12MP',
    memory: '4GB RAM',
    chipset: 'Snapdragon 820',
    batteryMaH: '4000mAh',
    price: 'About 300 EUR',
    id: 79
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-gear-s2.jpg',
    name: 'Samsung Gear S2',
    size: '47g, 11.4mm thickness',
    os: 'Tizen-based wearable platform',
    storage: '4GB storage, no card slot',
    displaySize: '1.2"',
    cameraSize: 'NO',
    memory: '512MB RAM',
    chipset: 'Exynos 3250 Dual',
    batteryMaH: '250mAh',
    price: 'About 220 EUR',
    id: 80
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s7-edge-usa.jpg',
    name: 'Samsung Galaxy S7 edge (USA)',
    size: '157g, 7.7mm thickness',
    os: 'Android 6.0',
    storage: '32GB storage, microSD card slot',
    displaySize: '5.5"',
    cameraSize: '12MP',
    memory: '4GB RAM',
    chipset: 'Snapdragon 820',
    batteryMaH: '3600mAh',
    price: 'About 300 EUR',
    id: 81
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-note5.jpg',
    name: 'Samsung Galaxy Note5 Duos',
    size: '171g, 7.6mm thickness',
    os: 'Android 5.1.1, up to 7.0',
    storage: '32/64GB storage, no card slot',
    displaySize: '5.7"',
    cameraSize: '16MP',
    memory: '4GB RAM',
    chipset: 'Exynos 7420 Octa',
    batteryMaH: '3000mAh',
    price: 'About 600 EUR',
    id: 82
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-j2-2016-new.jpg',
    name: 'Samsung Galaxy J2 (2016)',
    size: '138g, 8mm thickness',
    os: 'Android 6.0.1',
    storage: '8GB storage, microSD card slot',
    displaySize: '5.0"',
    cameraSize: '8MP',
    memory: '1.5GB RAM',
    chipset: 'Spreadtrum SC8830',
    batteryMaH: '2600mAh',
    price: 'About 300 EUR',
    id: 83
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s7-edge-.jpg',
    name: 'Samsung Galaxy S7 edge',
    size: '157g, 7.7mm thickness',
    os: 'Android 6.0, up to 7.0',
    storage: '32/64/128GB storage, microSD card slot',
    displaySize: '5.5"',
    cameraSize: '12MP',
    memory: '4GB RAM',
    chipset: 'Snapdragon 820',
    batteryMaH: '3600mAh',
    price: 'About 300 EUR',
    id: 84
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-j3.jpg',
    name: 'Samsung Galaxy J3 (2016)',
    size: '138g, 7.9mm thickness',
    os: 'Android 5.1.1 or Android 6.0',
    storage: '8/16GB storage, microSD card slot',
    displaySize: '5.0"',
    cameraSize: '8MP',
    memory: '2GB RAM',
    chipset: 'Spreadtrum SC9830',
    batteryMaH: '2600mAh',
    price: 'About 300 EUR',
    id: 85
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-tab-s2-97.jpg',
    name: 'Samsung Galaxy Tab S2 9.7', size: '389g (Wi-Fi) / 392g (LTE), 5.6mm thickness',
    os: 'Android 5.0.2, up to 6.0.1 - T810…',
    storage: '32/64GB storage, microSD card slot',
    displaySize: '9.7"',
    cameraSize: '8MP',
    memory: '3GB RAM',
    chipset: 'Exynos 5433',
    batteryMaH: '5870mAh',
    price: 'About 520 EUR',
    id: 86
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-guru-plus.jpg',
    name: 'Samsung Guru Plus ', size: '66g, 13.2mm thickness',
    os: 'Feature phone',
    storage: '4MB RAM storage, no card slot',
    displaySize: '1.5"',
    cameraSize: 'NO',
    memory: '4MB RAM',
    chipset: '',
    batteryMaH: '800mAh',
    price: 'About 20 EUR',
    id: 87
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-tab-e-sm-t561.jpg',
    name: 'Samsung Galaxy Tab E 9.6', size: '490g (Wi-Fi)/ 495g (3G), 8.5mm thickness',
    os: 'Android 5.1',
    storage: '8/16GB storage, microSD card slot',
    displaySize: '9.6"',
    cameraSize: '5MP',
    memory: '1.5GB RAM',
    chipset: '',
    batteryMaH: '5000mAh',
    price: 'About 200 EUR',
    id: 88
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-v-plus-sm-g318.jpg',
    name: 'Samsung Galaxy V Plus', size: '123g, 10.7mm thickness',
    os: 'Android 4.4.2',
    storage: '4GB storage, microSD card slot',
    displaySize: '4.0"',
    cameraSize: '3MP',
    memory: '512MB RAM',
    chipset: '',
    batteryMaH: '1500mAh',
    price: 'About 70 EUR',
    id: 89
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-j7-nxt-sm-j701fds.jpg',
    name: 'Samsung Galaxy J7 Nxt', size: '170g, 7.6mm thickness',
    os: 'Android 7.0',
    storage: '16GB storage, microSD card slot',
    displaySize: '5.5"',
    cameraSize: '13MP',
    memory: '2GB RAM',
    chipset: 'Exynos 7870 Octa',
    batteryMaH: '3000mAh',
    price: 'About 180 EUR',
    id: 90
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s6-active.jpg',
    name: 'Samsung Galaxy S6 active', size: '170g, 8.6mm thickness',
    os: 'Android 5.0.2, up to 6.0.1',
    storage: '32/64GB storage, no card slot',
    displaySize: '5.1"',
    cameraSize: '16MP',
    memory: '3GB RAM',
    chipset: 'Exynos 7420 Octa',
    batteryMaH: '3500mAh',
    price: 'About 300 EUR',
    id: 91
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-tab-a-and-s-pen.jpg',
    name: 'Samsung Galaxy Tab A &amp; S Pen', size: '490g, 7.5mm thickness',
    os: 'Android 5.0',
    storage: '16GB storage, microSD card slot',
    displaySize: '9.7"',
    cameraSize: '5MP',
    memory: '2GB RAM',
    chipset: '',
    batteryMaH: '6000mAh',
    price: 'About 340 EUR',
    id: 92
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a8-ds.jpg',
    name: 'Samsung Galaxy A8 Duos', size: '151g, 5.9mm thickness',
    os: 'Android 5.1, up to 6.0',
    storage: '32GB storage, microSD card slot',
    displaySize: '5.7"',
    cameraSize: '16MP',
    memory: '2GB RAM',
    chipset: 'Snapdragon 615',
    batteryMaH: '3050mAh',
    price: 'About 300 EUR',
    id: 93
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-xcover-3.jpg',
    name: 'Samsung Xcover 550', size: '124g, 14mm thickness',
    os: 'Feature phone',
    storage: '256MB storage, microSD card slot',
    displaySize: '2.4"',
    cameraSize: '3MP',
    memory: '128MB RAM',
    chipset: 'Spreadtrum SC7703',
    batteryMaH: '1500mAh',
    price: 'About 110 EUR',
    id: 94
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-tab-s2-80r1.jpg',
    name: 'Samsung Galaxy Tab S2 8.0', size: '265g (Wi-Fi) / 272g (LTE), 5.6mm thickness',
    os: 'Android 5.0.2, up to 6.0.1 - T710',
    storage: '32/64GB storage, microSD card slot',
    displaySize: '8.0"',
    cameraSize: '8MP',
    memory: '3GB RAM',
    chipset: 'Exynos 5433',
    batteryMaH: '4000mAh',
    price: 'About 440 EUR',
    id: 95
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-j7-j700f.jpg',
    name: 'Samsung Galaxy J7', size: '171g, 7.5mm thickness',
    os: 'Android 5.1, up to 6.0.1',
    storage: '16GB storage, microSD card slot',
    displaySize: '5.5"',
    cameraSize: '13MP',
    memory: '1.5GB RAM',
    chipset: 'Snapdragon 615',
    batteryMaH: '3000mAh',
    price: 'About 300 EUR',
    id: 96
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a8-.jpg',
    name: 'Samsung Galaxy A8', size: '151g, 5.9mm thickness',
    os: 'Android 5.1.1, up to 6.0',
    storage: '32GB storage, microSD card slot',
    displaySize: '5.7"',
    cameraSize: '16MP',
    memory: '2GB RAM',
    chipset: 'Snapdragon 615',
    batteryMaH: '3050mAh',
    price: 'About 300 EUR',
    id: 97
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-tab-3-v.jpg',
    name: 'Samsung Galaxy Tab 3 V', size: '322g, 9.7mm thickness',
    os: 'Android 4.4',
    storage: '8GB storage, microSD card slot',
    displaySize: '7.0"',
    cameraSize: '2MP',
    memory: '1GB RAM',
    chipset: '',
    batteryMaH: '3600mAh',
    price: 'About 130 EUR',
    id: 98
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-tab-4-101-2015.jpg',
    name: 'Samsung Galaxy Tab 4 10.1 (2015)', size: '487g, 7.9mm thickness',
    os: 'Android 4.4.4, up to 5.1.1',
    storage: '16GB storage, microSD card slot',
    displaySize: '10.1"',
    cameraSize: '3MP',
    memory: '1.5GB RAM',
    chipset: 'Snapdragon 410',
    batteryMaH: '6800mAh',
    price: 'About 280 EUR',
    id: 99
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-tab-a-80.jpg',
    name: 'Samsung Galaxy Tab A 9.7', size: '450g (Wi-Fi), 453g (LTE), 7.5mm thickness',
    os: 'Android 5.0, up to 6.0.1',
    storage: '16GB storage, microSD card slot',
    displaySize: '9.7"',
    cameraSize: '5MP',
    memory: '2GB RAM',
    chipset: '',
    batteryMaH: '6000mAh',
    price: 'About 250 EUR',
    id: 100
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-j5-sm-j500f.jpg',
    name: 'Samsung Galaxy J5', size: '146g, 7.9mm thickness',
    os: 'Android 5.1, up to 6.0.1',
    storage: '8/16GB storage, microSD card slot',
    displaySize: '5.0"',
    cameraSize: '13MP',
    memory: '1.5GB RAM',
    chipset: 'Snapdragon 410',
    batteryMaH: '2600mAh',
    price: 'About 160 EUR',
    id: 101
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-xcover-3-new.jpg',
    name: 'Samsung Galaxy Xcover 3', size: '154g, 10mm thickness',
    os: 'Android 4.4.4',
    storage: '8GB storage, microSD card slot',
    displaySize: '4.5"',
    cameraSize: '5MP',
    memory: '1.5GB RAM',
    chipset: 'Marvell Armada PXA1908',
    batteryMaH: '2200mAh',
    price: 'About 220 EUR',
    id: 102
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-a7.jpg',
    name: 'Samsung Galaxy A7', size: '141g, 6.3mm thickness',
    os: 'Android 4.4.4, up to 5.0.2',
    storage: '16GB storage, microSD card slot',
    displaySize: '5.5"',
    cameraSize: '13MP',
    memory: '2GB RAM',
    chipset: 'Snapdragon 615',
    batteryMaH: '2600mAh',
    price: 'About 300 EUR',
    id: 103
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-j1-sm-j100h1.jpg',
    name: 'Samsung Galaxy J1', size: '122g, 8.9mm thickness',
    os: 'Android 4.4.4',
    storage: '4GB storage, microSD card slot',
    displaySize: '4.3"',
    cameraSize: '5MP',
    memory: '512MB RAM',
    chipset: 'Spreadtrum',
    batteryMaH: '1850mAh',
    price: 'About 110 EUR',
    id: 104
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-z-1.jpg',
    name: 'Samsung Z1', size: '112g, 9.7mm thickness',
    os: 'Tizen 2.3',
    storage: '4GB storage, microSD card slot',
    displaySize: '4.0"',
    cameraSize: '3MP',
    memory: '768MB RAM',
    chipset: 'Spreadtrum SC7727S',
    batteryMaH: '1500mAh',
    price: 'About 80 EUR',
    id: 105
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-a7.jpg',
    name: 'Samsung Galaxy A7 Duos', size: '141g, 6.3mm thickness',
    os: 'Android 4.4.4',
    storage: '16GB storage, microSD card slot',
    displaySize: '5.5"',
    cameraSize: '13MP',
    memory: '2GB RAM',
    chipset: 'Snapdragon 615',
    batteryMaH: '2600mAh',
    price: 'About 300 EUR',
    id: 106
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-grand-max.jpg',
    name: 'Samsung Galaxy Grand Max', size: '161g, 7.9mm thickness',
    os: 'Android 4.4.4',
    storage: '16GB storage, microSD card slot',
    displaySize: '5.25"',
    cameraSize: '13MP',
    memory: '1.5GB RAM',
    chipset: 'Snapdragon 410',
    batteryMaH: '2500mAh',
    price: 'About 260 EUR',
    id: 107
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-a3.jpg',
    name: 'Samsung Galaxy A3', size: '110.3g, 6.9mm thickness',
    os: 'Android 4.4.4, up to 6.0.1',
    storage: '16GB storage, microSD card slot',
    displaySize: '4.5"',
    cameraSize: '8MP',
    memory: '1.5GB RAM',
    chipset: 'Snapdragon 410',
    batteryMaH: '1900mAh',
    price: 'About 300 EUR',
    id: 108
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-a5.jpg',
    name: 'Samsung Galaxy A5', size: '123g, 6.7mm thickness',
    os: 'Android 4.4.4, 6.0.1',
    storage: '16GB storage, microSD card slot',
    displaySize: '5.0"',
    cameraSize: '13MP',
    memory: '2GB RAM',
    chipset: 'Snapdragon 410',
    batteryMaH: '2300mAh',
    price: 'About 300 EUR',
    id: 109
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s6.jpg',
    name: 'Samsung Galaxy S6', size: '138g, 6.8mm thickness',
    os: 'Android 5.0.2, up to 7.0',
    storage: '32/64/128GB storage, no card slot',
    displaySize: '5.1"',
    cameraSize: '16MP',
    memory: '3GB RAM',
    chipset: 'Exynos 7420 Octa',
    batteryMaH: '2550mAh',
    price: 'About 300 EUR',
    id: 110
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-a3.jpg',
    name: 'Samsung Galaxy A3 Duos', size: '110.3g, 6.9mm thickness',
    os: 'Android 4.4.4, up to 5.0.2',
    storage: '16GB storage, microSD card slot',
    displaySize: '4.5"',
    cameraSize: '8MP',
    memory: '1GB RAM',
    chipset: 'Snapdragon 410',
    batteryMaH: '1900mAh',
    price: 'About 300 EUR',
    id: 111
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-grand-prime-sm-g530h.jpg',
    name: 'Samsung Galaxy Grand Prime', size: '156g, 8.6mm thickness',
    os: 'Android 4.4.4',
    storage: '8GB storage, microSD card slot',
    displaySize: '5.0"',
    cameraSize: '8MP',
    memory: '1GB RAM',
    chipset: 'Snapdragon 410',
    batteryMaH: '2600mAh',
    price: 'About 300 EUR',
    id: 112
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-v1.jpg',
    name: 'Samsung Galaxy V', size: '123g, 10.7mm thickness',
    os: 'Android 4.4.2',
    storage: '4GB storage, microSD card slot',
    displaySize: '4.0"',
    cameraSize: '3MP',
    memory: '512MB RAM',
    chipset: '',
    batteryMaH: '1500mAh',
    price: 'About 80 EUR',
    id: 113
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-pocket-2.jpg',
    name: 'Samsung Galaxy Pocket 2', size: '107g, 11.7mm thickness',
    os: 'Android 4.4.2',
    storage: '4GB storage, microSD card slot',
    displaySize: '3.3"',
    cameraSize: '2MP',
    memory: '512MB RAM',
    chipset: 'Spreadtrum SC7715',
    batteryMaH: '1200mAh',
    price: 'About 100 EUR',
    id: 114
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-note-4-duos-sm-n9100.jpg',
    name: 'Samsung Galaxy Note 4 Duos', size: '175g, 8.5mm thickness',
    os: 'Android 4.4.4, up to 6.0.1',
    storage: '16GB storage, microSD card slot',
    displaySize: '5.7"',
    cameraSize: '16MP',
    memory: '3GB RAM',
    chipset: 'Snapdragon 805',
    batteryMaH: '3000mAh',
    price: 'About 500 EUR',
    id: 115
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-gear-2.jpg',
    name: 'Samsung Gear 2', size: '68g, 10mm thickness',
    os: 'Tizen-based wearable platform',
    storage: '4GB storage, no card slot',
    displaySize: '1.63"',
    cameraSize: '2MP',
    memory: '512MB RAM',
    chipset: 'Exynos 3250 Dual',
    batteryMaH: '300mAh',
    price: 'About 230 EUR',
    id: 116
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-avant.jpg',
    name: 'Samsung Galaxy Avant', size: '136.9g, 9.9mm thickness',
    os: 'Android 4.4.2',
    storage: '16GB storage, microSD card slot',
    displaySize: '4.5"',
    cameraSize: '5MP',
    memory: '1.5GB RAM',
    chipset: 'Snapdragon 400',
    batteryMaH: '2100mAh',
    price: 'About 160 EUR',
    id: 117
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-gear-s-new.jpg',
    name: 'Samsung Gear S', size: '67g, 12.5mm thickness',
    os: 'Tizen-based wearable platform',
    storage: '4GB storage, no card slot',
    displaySize: '2.0"',
    cameraSize: 'NO',
    memory: '512MB RAM',
    chipset: 'Snapdragon 400',
    batteryMaH: '300mAh',
    price: 'About 300 EUR',
    id: 118
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-metro-312.jpg',
    name: 'Samsung Metro 312', size: '74g, 13.1mm thickness',
    os: 'Feature phone',
    storage: 'microSD card slot',
    displaySize: '2.0"',
    cameraSize: '0.3MP',
    memory: '',
    chipset: '',
    batteryMaH: '1000mAh',
    price: 'About 300 EUR',
    id: 119
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-gear-live.jpg',
    name: 'Samsung Gear Live', size: '59g, 8.9mm thickness',
    os: 'Android Wear OS',
    storage: '4GB storage, no card slot',
    displaySize: '1.63"',
    cameraSize: 'NO',
    memory: '512MB RAM',
    chipset: 'Snapdragon 400',
    batteryMaH: '300mAh',
    price: 'About 300 EUR',
    id: 120
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s6-edge.jpg',
    name: 'Samsung Galaxy S6 edge', size: '132g, 7mm thickness',
    os: 'Android 5.0.2, up to 7.0',
    storage: '32/64/128GB storage, no card slot',
    displaySize: '5.1"',
    cameraSize: '16MP',
    memory: '3GB RAM',
    chipset: 'Exynos 7420 Octa',
    batteryMaH: '2600mAh',
    price: 'About 300 EUR',
    id: 121
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-ace-style-lte.jpg',
    name: 'Samsung Galaxy Ace Style LTE G357', size: '126g, 9.1mm thickness',
    os: 'Android 4.4.4',
    storage: '8GB storage, microSD card slot',
    displaySize: '4.3"',
    cameraSize: '5MP',
    memory: '1GB RAM',
    chipset: 'Snapdragon 410',
    batteryMaH: '1900mAh',
    price: 'About 200 EUR',
    id: 122
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-v-2014.jpg',
    name: 'Samsung Galaxy Ace NXT', size: '123g, 10.7mm thickness',
    os: 'Android 4.4.2',
    storage: '4GB storage, microSD card slot',
    displaySize: '4.0"',
    cameraSize: '3MP',
    memory: '512MB RAM',
    chipset: '',
    batteryMaH: '1500mAh',
    price: 'About 90 EUR',
    id: 123
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s5-g900f.jpg',
    name: 'Samsung Galaxy S5 Plus', size: '145g, 8.1mm thickness',
    os: 'Android 4.4.2',
    storage: '16/32GB storage, microSD card slot',
    displaySize: '5.1"',
    cameraSize: '16MP',
    memory: '2GB RAM',
    chipset: 'Snapdragon 805',
    batteryMaH: '2800mAh',
    price: 'About 380 EUR',
    id: 124
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s5-sport.jpg',
    name: 'Samsung Galaxy S5 Sport', size: '158g, 8.9mm thickness',
    os: 'Android 4.4.2, up to 6.0',
    storage: '16GB storage, microSD card slot',
    displaySize: '5.1"',
    cameraSize: '16MP',
    memory: '2GB RAM',
    chipset: 'Snapdragon 801',
    batteryMaH: '2800mAh',
    price: 'About 500 EUR',
    id: 125
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-note-4-new.jpg',
    name: 'Samsung Galaxy Note 4', size: '176g, 8.5mm thickness',
    os: 'Android 4.4.4, up to 6.0.1',
    storage: '32GB storage, microSD card slot',
    displaySize: '5.7"',
    cameraSize: '16MP',
    memory: '3GB RAM',
    chipset: 'Snapdragon 805',
    batteryMaH: '3220mAh',
    price: 'About 300 EUR',
    id: 126
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-gear-2-neo.jpg',
    name: 'Samsung Gear 2 Neo', size: '55g, 9.9mm thickness',
    os: 'Tizen-based wearable platform',
    storage: '4GB storage, no card slot',
    displaySize: '1.63"',
    cameraSize: 'NO',
    memory: '512MB RAM',
    chipset: 'Exynos 3250 Dual',
    batteryMaH: '300mAh',
    price: 'About 170 EUR',
    id: 127
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-tab-s-8.4.jpg',
    name: 'Samsung Galaxy Tab S 8.4', size: '294g, 6.6mm thickness',
    os: 'Android 4.4.2, up to 6.0',
    storage: '16/32GB storage, microSD card slot',
    displaySize: '8.4"',
    cameraSize: '8MP',
    memory: '3GB RAM',
    chipset: 'Exynos 5420 Octa',
    batteryMaH: '4900mAh',
    price: 'About 300 EUR',
    id: 128
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-gran-prime-duos-tv-sm-g530bt.jpg',
    name: 'Samsung Galaxy Grand Prime Duos TV', size: '152g, 8.6mm thickness',
    os: 'Android 4.4.2',
    storage: '8GB storage, microSD card slot',
    displaySize: '5.0"',
    cameraSize: '8MP',
    memory: '1GB RAM',
    chipset: 'Snapdragon 410',
    batteryMaH: '2600mAh',
    price: 'About 150 EUR',
    id: 129
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s6-cdma.jpg',
    name: 'Samsung Galaxy S6 (USA)', size: '140g, 6.9mm thickness',
    os: 'Android 5.0.2, up to 5.1',
    storage: '32/64/128GB storage, no card slot',
    displaySize: '5.1"',
    cameraSize: '16MP',
    memory: '3GB RAM',
    chipset: 'Exynos 7420 Octa',
    batteryMaH: '2550mAh',
    price: 'About 410 EUR',
    id: 130
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-j1-sm-j100h1.jpg',
    name: 'Samsung Galaxy J1 4G', size: '122g, 8.9mm thickness',
    os: 'Android 4.4.4',
    storage: '4GB storage, microSD card slot',
    displaySize: '4.3"',
    cameraSize: '5MP',
    memory: '768MB RAM',
    chipset: '',
    batteryMaH: '1850mAh',
    price: 'About 120 EUR',
    id: 131
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s6.jpg',
    name: 'Samsung Galaxy S6 Duos', size: '138g, 6.8mm thickness',
    os: 'Android OS',
    storage: '32/64/128GB storage, no card slot',
    displaySize: '5.1"',
    cameraSize: '16MP',
    memory: '3GB RAM',
    chipset: 'Exynos 7420 Octa',
    batteryMaH: '2550mAh',
    price: 'About 400 EUR',
    id: 132
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-tab-3-lite.jpg',
    name: 'Samsung Galaxy Tab 3 Lite 7.0 VE', size: '310g, 9.7mm thickness',
    os: 'Android 4.4.4',
    storage: '8GB storage, microSD card slot',
    displaySize: '7.0"',
    cameraSize: '2MP',
    memory: '1GB RAM',
    chipset: 'Spreadtrum SC8830',
    batteryMaH: '3600mAh',
    price: 'About 120 EUR',
    id: 133
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-j2.jpg',
    name: 'Samsung Galaxy J2', size: '129g, 8.4mm thickness',
    os: 'Android 5.1.1',
    storage: '8GB storage, microSD card slot',
    displaySize: '4.7"',
    cameraSize: '5MP',
    memory: '1GB RAM',
    chipset: 'Exynos 3475 Quad',
    batteryMaH: '2000mAh',
    price: 'About 300 EUR',
    id: 134
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-e5.jpg',
    name: 'Samsung Galaxy E5', size: '7.3mm thickness',
    os: 'Android 4.4.4',
    storage: '16GB storage, microSD card slot',
    displaySize: '5.0"',
    cameraSize: '8MP',
    memory: '1.5GB RAM',
    chipset: 'Snapdragon 410',
    batteryMaH: '2400mAh',
    price: 'About 200 EUR',
    id: 135
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-tab-a8.jpg',
    name: 'Samsung Galaxy Tab A 8.0', size: '313g, 7.4mm thickness',
    os: 'Android 5.0',
    storage: '16GB storage, microSD card slot',
    displaySize: '8.0"',
    cameraSize: '5MP',
    memory: '2GB RAM',
    chipset: '',
    batteryMaH: '4200mAh',
    price: 'About 210 EUR',
    id: 136
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s6-edge-cdma.jpg',
    name: 'Samsung Galaxy S6 edge (USA)', size: '132g, 7.1mm thickness',
    os: 'Android 5.0.2, up to 5.1',
    storage: '32/64/128GB storage, no card slot',
    displaySize: '5.1"',
    cameraSize: '16MP',
    memory: '3GB RAM',
    chipset: 'Exynos 7420 Octa',
    batteryMaH: '2600mAh',
    price: 'About 600 EUR',
    id: 137
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-tab-active.jpg',
    name: 'Samsung Galaxy Tab Active LTE', size: '393g, 9.7mm thickness',
    os: 'Android 4.4.2',
    storage: '16GB storage, microSD card slot',
    displaySize: '8.0"',
    cameraSize: '3MP',
    memory: '1.5GB RAM',
    chipset: 'Snapdragon 400',
    batteryMaH: '4450mAh',
    price: 'About 600 EUR',
    id: 138
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s5-mini-duos.jpg',
    name: 'Samsung Galaxy S5 mini Duos', size: '118g, 9.1mm thickness',
    os: 'Android 4.4.4, up to 6.0.1',
    storage: '16GB storage, microSD card slot',
    displaySize: '4.5"',
    cameraSize: '8MP',
    memory: '1.5GB RAM',
    chipset: '',
    batteryMaH: '2100mAh',
    price: 'About 250 EUR',
    id: 139
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-alpha.jpg',
    name: 'Samsung Galaxy Alpha (S801)', size: '115g, 6.7mm thickness',
    os: 'Android 4.4.4',
    storage: '32GB storage, no card slot',
    displaySize: '4.7"',
    cameraSize: '12MP',
    memory: '2GB RAM',
    chipset: 'Snapdragon 801',
    batteryMaH: '1860mAh',
    price: 'About 450 EUR',
    id: 140
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-a5.jpg',
    name: 'Samsung Galaxy A5 Duos', size: '123g, 6.7mm thickness',
    os: 'Android 4.4.4, up to 5.0.2',
    storage: '16GB storage, microSD card slot',
    displaySize: '5.0"',
    cameraSize: '13MP',
    memory: '2GB RAM',
    chipset: 'Snapdragon 410',
    batteryMaH: '2300mAh',
    price: 'About 300 EUR',
    id: 141
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-star-2.jpg',
    name: 'Samsung Galaxy Star 2', size: '107.6g, 11.8mm thickness',
    os: 'Android 4.4.2',
    storage: '4GB storage, microSD card slot',
    displaySize: '3.5"',
    cameraSize: '2MP',
    memory: '512MB RAM',
    chipset: 'SC6815A',
    batteryMaH: '1300mAh',
    price: 'About 120 EUR',
    id: 142
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-tab-s-8.4.jpg',
    name: 'Samsung Galaxy Tab S 8.4 LTE', size: '298g, 6.6mm thickness',
    os: 'Android 4.4.2, up to 6.0',
    storage: '16/32GB storage, microSD card slot',
    displaySize: '8.4"',
    cameraSize: '8MP',
    memory: '3GB RAM',
    chipset: 'Snapdragon 800',
    batteryMaH: '4900mAh',
    price: 'About 300 EUR',
    id: 143
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-ace-4.jpg',
    name: 'Samsung Galaxy Ace 4', size: '123.8g, 10.8mm thickness',
    os: 'Android 4.4.2',
    storage: '4GB storage, microSD card slot',
    displaySize: '4.0"',
    cameraSize: '5MP',
    memory: '512MB RAM',
    chipset: '',
    batteryMaH: '1500mAh',
    price: 'About 220 EUR',
    id: 144
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s5-lte-a.jpg',
    name: 'Samsung Galaxy S5 LTE-A G906S', size: '145g, 8.1mm thickness',
    os: 'Android 4.4.2, up to 6.0.1',
    storage: '16/32GB storage, microSD card slot',
    displaySize: '5.1"',
    cameraSize: '16MP',
    memory: '3GB RAM',
    chipset: 'Snapdragon 805',
    batteryMaH: '2800mAh',
    price: 'About 550 EUR',
    id: 145
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/Samsung-Z.jpg',
    name: 'Samsung Z', size: '136g, 8.5mm thickness',
    os: 'Tizen 2.2.1',
    storage: '16GB storage, microSD card slot',
    displaySize: '4.8"',
    cameraSize: '8MP',
    memory: '2GB RAM',
    chipset: '',
    batteryMaH: '2600mAh',
    price: 'About 300 EUR',
    id: 146
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-e7.jpg',
    name: 'Samsung Galaxy E7', size: '141g, 7.3mm thickness',
    os: 'Android 4.4.4, up to 5.1.1',
    storage: '16GB storage, microSD card slot',
    displaySize: '5.5"',
    cameraSize: '13MP',
    memory: '2GB RAM',
    chipset: 'Snapdragon 410',
    batteryMaH: '2950mAh',
    price: 'About 300 EUR',
    id: 147
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-core-prime.jpg',
    name: 'Samsung Galaxy Core Prime', size: '130g, 8.8mm thickness',
    os: 'Android 4.4.4, up to 5.1.1',
    storage: '8GB storage, microSD card slot',
    displaySize: '4.5"',
    cameraSize: '5MP',
    memory: '1GB RAM',
    chipset: 'Snapdragon 410',
    batteryMaH: '2000mAh',
    price: 'About 300 EUR',
    id: 148
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-ace-4.jpg',
    name: 'Samsung Galaxy Ace 4 LTE G313', size: '130.3g, 11mm thickness',
    os: 'Android 4.4.2',
    storage: '4GB storage, microSD card slot',
    displaySize: '4.0"',
    cameraSize: '5MP',
    memory: '1GB RAM',
    chipset: '',
    batteryMaH: '1800mAh',
    price: 'About 250 EUR',
    id: 149
  },
  {
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-metro-360.jpg',
    name: 'Samsung Metro 360', size: '83g, 11.4mm thickness',
    os: 'Feature phone',
    storage: '64MB RAM storage, microSD card slot',
    displaySize: '2.4"',
    cameraSize: '3MP',
    memory: '64MB RAM',
    chipset: '',
    batteryMaH: '1000mAh',
    price: 'About 50 EUR',
    id: 150
  },
  ];

  getAll() { return this.items; }

  getById(id) {
	    return this.items.find(x => x.id === id);

  }
  add(product: any){
    const last = this.items[this.items.length-1];
    product.id = last.id + 1;
    this.items.push(product);
  }
}
