import { Injectable } from '@angular/core';

@Injectable() export class ItemsService {
  constructor() { }

  items = [{
    name: 'Samsung Galaxy J7 Pro',
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-j7-pro.jpg',
    size: '181g, 7.9mm thickness',
    os: 'Android 7.1',
    storage: '32/64GB storage, microSD card slot',
    displaySize: '5.5"',
    cameraSize: '13MP',
    RAM: '3GB RAM',
    chipset: 'Exynos 7870 Octa',
    batteryMaH: '3600mAh',
    price: 'About 300 EUR'
  }, {
    name: 'Samsung Gear S3 classic LTE',
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-gear-s3-classic-lte.jpg',
    size: '57g, 12.9mm thickness',
    os: 'Tizen-based wearable platform 2.3.2',
    storage: '4GB storage, no card slot',
    displaySize: '1.3"',
    cameraSize: 'NO',
    RAM: '768MB RAM',
    chipset: 'Exynos 7270',
    batteryMaH: '380mAh',
    price: 'About 300 EUR'
  }, {
    name: 'Samsung Galaxy J1 Ace',
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-j1-ace.jpg',
    size: '131g, 9.5mm thickness',
    os: 'Android 4.4.4',
    storage: '4GB storage, microSD card slot',
    displaySize: '4.3"',
    cameraSize: '5MP',
    RAM: '1GB RAM',
    chipset: 'Spreadtrum SC9830',
    batteryMaH: '1850mAh',
    price: 'About 140 EUR'
  }, {
    name: 'Samsung Galaxy A9 Pro (2016)',
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a9-pro1.jpg',
    size: '210g, 7.9mm thickness',
    os: 'Android 6.0.1',
    storage: '32GB storage, microSD card slot',
    displaySize: '6.0"',
    cameraSize: '16MP',
    RAM: '4GB RAM',
    chipset: 'Snapdragon 652',
    batteryMaH: '5000mAh',
    price: 'About 500 EUR'
  }, {
    name: 'Samsung Galaxy Tab S3 9.7',
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-tab-s3-97-sm-t825.jpg',
    size: '429g (Wi-Fi)/ 434g (LTE), 6mm thickness',
    os: 'Android 7.0',
    storage: '32GB storage, microSD card slot',
    displaySize: '9.7"',
    cameraSize: '13MP',
    RAM: '4GB RAM',
    chipset: 'Snapdragon 820',
    batteryMaH: '6000mAh',
    price: 'About 750 EUR'
  }, {
    name: 'Samsung Galaxy A7 (2017)',
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a7-2017.jpg',
    size: '186g, 7.9mm thickness',
    os: 'Android 6.0.1, up to 7.0',
    storage: '32GB storage, microSD card slot',
    displaySize: '5.7"',
    cameraSize: '16MP',
    RAM: '3GB RAM',
    chipset: 'Exynos 7880 Octa',
    batteryMaH: '3600mAh',
    price: 'About 300 EUR'
  }, {
    name: 'Samsung Galaxy J7 Prime',
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-j7-prime.jpg',
    size: '167g, 8mm thickness',
    os: 'Android 6.0.1',
    storage: '16/32GB storage, microSD card slot',
    displaySize: '5.5"',
    cameraSize: '13MP',
    RAM: '3GB RAM',
    chipset: 'Exynos 7870 Octa',
    batteryMaH: '3300mAh',
    price: 'About 280 EUR'
  }, {
    name: 'Samsung Z4',
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-z4.jpg',
    size: '143g, 10.3mm thickness',
    os: 'Tizen 3.0',
    storage: '8GB storage, microSD card slot',
    displaySize: '4.5"',
    cameraSize: '5MP',
    RAM: '1GB RAM',
    chipset: '',
    batteryMaH: '2050mAh',
    price: 'About 300 EUR'
  }, {
    name: 'Samsung Galaxy C7 Pro',
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-c7-pro.jpg',
    size: '172g, 7mm thickness',
    os: 'Android 6.0.1',
    storage: '64GB storage, microSD card slot',
    displaySize: '5.7"',
    cameraSize: '16MP',
    RAM: '4GB RAM',
    chipset: 'Snapdragon 626',
    batteryMaH: '3300mAh',
    price: 'About 420 EUR'
  }, {
    name: 'Samsung Galaxy Note5 (USA)',
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-note5.jpg',
    size: '171g, 7.6mm thickness',
    os: 'Android 5.1.1, up to 7.0',
    storage: '32/64GB storage, no card slot',
    displaySize: '5.7"',
    cameraSize: '16MP',
    RAM: '4GB RAM',
    chipset: 'Exynos 7420 Octa',
    batteryMaH: '3000mAh',
    price: 'About 540 EUR'
  }, {
    name: 'Samsung Galaxy Note7 (USA)',
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-note7-usa.jpg',
    size: '169g, 7.9mm thickness',
    os: 'Android 6.0.1',
    storage: '64GB storage, microSD card slot',
    displaySize: '5.7"',
    cameraSize: '12MP',
    RAM: '4GB RAM',
    chipset: 'Snapdragon 820',
    batteryMaH: '3500mAh',
    price: 'About 300 EUR'
  }, {
    name: 'Samsung Galaxy Tab A 10.1 (2016)',
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-tab-a-101-2016.jpg',
    size: '525g, 8.2mm thickness',
    os: 'Android 6.0, up to 7.0',
    storage: '16GB storage, microSD card slot',
    displaySize: '10.1"',
    cameraSize: '8MP',
    RAM: '2GB RAM',
    chipset: 'Exynos 7870',
    batteryMaH: '7300mAh',
    price: 'About 220 EUR'
  }, {
    name: 'Samsung Z3 Corporate Edition',
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-z3.jpg',
    size: '7.9mm thickness',
    os: 'Tizen 2.4',
    storage: '8GB storage, microSD card slot',
    displaySize: '5.0"',
    cameraSize: '8MP',
    RAM: '1GB RAM',
    chipset: 'Snapdragon 410',
    batteryMaH: '2600mAh',
    price: 'About 270 EUR'
  }, {
    name: 'Samsung Galaxy Tab S2 8.0',
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-tab-s2-80r1.jpg',
    size: '265g (Wi-Fi) / 272g (LTE), 5.6mm thickness',
    os: 'Android 5.0.2, up to 6.0.1 - T710',
    storage: '32/64GB storage, microSD card slot',
    displaySize: '8.0"',
    cameraSize: '8MP',
    RAM: '3GB RAM',
    chipset: 'Exynos 5433',
    batteryMaH: '4000mAh',
    price: 'About 440 EUR'
  }, {
    name: 'Samsung Galaxy On5',
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-on5.jpg',
    size: '149g, 8.5mm thickness',
    os: 'Android 5.1Android 6.0 - T-Mo…',
    storage: '8GB storage, microSD card slot',
    displaySize: '5.0"',
    cameraSize: '8MP',
    RAM: '1.5GB RAM',
    chipset: 'Exynos 3475 Quad',
    batteryMaH: '2600mAh',
    price: 'About 140 EUR'
  }, {
    name: 'Samsung Galaxy J2 Prime',
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-j2-prime-2016.jpg',
    size: '160g, 8.9mm thickness',
    os: 'Android 6.0',
    storage: '8GB storage, microSD card slot',
    displaySize: '5.0"',
    cameraSize: '8MP',
    RAM: '1.5GB RAM',
    chipset: 'MT6737T',
    batteryMaH: '2600mAh',
    price: 'About 300 EUR'
  }, {
    name: 'Samsung Galaxy Note5 Duos',
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-note5.jpg',
    size: '171g, 7.6mm thickness',
    os: 'Android 5.1.1, up to 7.0',
    storage: '32/64GB storage, no card slot',
    displaySize: '5.7"',
    cameraSize: '16MP',
    RAM: '4GB RAM',
    chipset: 'Exynos 7420 Octa',
    batteryMaH: '3000mAh',
    price: 'About 600 EUR'
  }, {
    name: 'Samsung Galaxy On5 Pro',
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-on5.jpg',
    size: '149g, 8.5mm thickness',
    os: 'Android 6.0',
    storage: '16GB storage, microSD card slot',
    displaySize: '5.0"',
    cameraSize: '8MP',
    RAM: '2GB RAM',
    chipset: 'Exynos 3475 Quad',
    batteryMaH: '2600mAh',
    price: 'About 150 EUR'
  }, {
    name: 'Samsung Galaxy A7 (2016)',
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a7-2016.jpg',
    size: '172g, 7.3mm thickness',
    os: 'Android 5.1.1, up to 7.0',
    storage: '16GB storage, microSD card slot',
    displaySize: '5.5"',
    cameraSize: '13MP',
    RAM: '3GB RAM',
    chipset: 'Exynos 7580 Octa',
    batteryMaH: '3300mAh',
    price: 'About 300 EUR'
  }, {
    name: 'Samsung Galaxy J1 Nxt',
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-j1-nxt.jpg',
    size: '123g, 10.8mm thickness',
    os: 'Android 5.1',
    storage: '8GB storage, microSD card slot',
    displaySize: '4.0"',
    cameraSize: '5MP',
    RAM: '1GB RAM',
    chipset: 'Spreadtrum SC9830',
    batteryMaH: '1500mAh',
    price: 'About 90 EUR'
  }, {
    name: 'Samsung Galaxy Tab J',
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-j-tablet1.jpg',
    size: '289g, 8.7mm thickness',
    os: 'Android 5.1',
    storage: '8GB storage, microSD card slot',
    displaySize: '7.0"',
    cameraSize: '8MP',
    RAM: '1.5GB RAM',
    chipset: 'Spreadtrum SC8830',
    batteryMaH: '4000mAh',
    price: 'About 300 EUR'
  }, {
    name: 'Samsung Galaxy On7',
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-on7-.jpg',
    size: '172g, 8.2mm thickness',
    os: 'Android 5.1, up to 6.0.1',
    storage: '8GB storage, microSD card slot',
    displaySize: '5.5"',
    cameraSize: '13MP',
    RAM: '1.5GB RAM',
    chipset: 'Snapdragon 410',
    batteryMaH: '3000mAh',
    price: 'About 180 EUR'
  }, {
    name: 'Samsung Z2',
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-z2.jpg',
    size: '127g, 10.8mm thickness',
    os: 'Tizen 2.4',
    storage: '8GB storage, microSD card slot',
    displaySize: '4.0"',
    cameraSize: '5MP',
    RAM: '1GB RAM',
    chipset: 'Spreadtrum SC9830',
    batteryMaH: '1500mAh',
    price: 'About 80 EUR'
  }, {
    name: 'Samsung Galaxy Note FE',
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-note-fe.jpg',
    size: '167g, 7.9mm thickness',
    os: 'Android 7.1.1',
    storage: '64GB storage, microSD card slot',
    displaySize: '5.7"',
    cameraSize: '12MP',
    RAM: '4GB RAM',
    chipset: 'Exynos 8890 Octa',
    batteryMaH: '3200mAh',
    price: 'About 540 EUR'
  }, {
    name: 'Samsung Galaxy J1 (2016)',
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-j1-2016.jpg',
    size: '131g, 8.9mm thickness',
    os: 'Android 5.1.1',
    storage: '8GB storage, microSD card slot',
    displaySize: '4.5"',
    cameraSize: '5MP',
    RAM: '1GB RAM',
    chipset: 'Spreadtrum SC9830',
    batteryMaH: '2050mAh',
    price: 'About 130 EUR'
  }, {
    name: 'Samsung Gear S3 frontier',
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-gear-s3-frontier-lte.jpg',
    size: '63g, 12.9mm thickness',
    os: 'Tizen-based wearable platform 2.3.2',
    storage: '4GB storage, no card slot',
    displaySize: '1.3"',
    cameraSize: 'NO',
    RAM: '768MB RAM',
    chipset: 'Exynos 7270',
    batteryMaH: '380mAh',
    price: 'About 350 EUR'
  }, {
    name: 'Samsung Galaxy J3 (2017)',
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-j3-2017.jpg',
    size: '142g, 8.2mm thickness',
    os: 'Android 7.0',
    storage: '16GB storage, microSD card slot',
    displaySize: '5.0"',
    cameraSize: '13MP',
    RAM: '2GB RAM',
    chipset: 'Exynos 7570 Quad',
    batteryMaH: '2400mAh',
    price: 'About 220 EUR'
  }, {
    name: 'Samsung Galaxy S7 edge (USA)',
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s7-edge-usa.jpg',
    size: '157g, 7.7mm thickness',
    os: 'Android 6.0',
    storage: '32GB storage, microSD card slot',
    displaySize: '5.5"',
    cameraSize: '12MP',
    RAM: '4GB RAM',
    chipset: 'Snapdragon 820',
    batteryMaH: '3600mAh',
    price: 'About 300 EUR'
  }, {
    name: 'Samsung Galaxy S4 mini I9195I',
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s4-mini-plus-gt-i9195i.jpg',
    size: '107g, 8.9mm thickness',
    os: 'Android 4.4.4',
    storage: '8GB storage, microSD card slot',
    displaySize: '4.3"',
    cameraSize: '8MP',
    RAM: '1.5GB RAM',
    chipset: 'Snapdragon 410',
    batteryMaH: '1900mAh',
    price: 'About 190 EUR'
  }, {
    name: 'Samsung Galaxy J5 (2016)',
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-j5-2016r.jpg',
    size: '159g, 8.1mm thickness',
    os: 'Android 6.0.1',
    storage: '16GB storage, microSD card slot',
    displaySize: '5.2"',
    cameraSize: '13MP',
    RAM: '2GB RAM',
    chipset: 'Snapdragon 410',
    batteryMaH: '3100mAh',
    price: 'About 300 EUR'
  }, {
    name: 'Samsung Galaxy J5 (2017)',
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-j5-2017-sm-j530.jpg',
    size: '160g, 8mm thickness',
    os: 'Android 7.0',
    storage: '16GB storage, microSD card slot',
    displaySize: '5.2"',
    cameraSize: '13MP',
    RAM: '3GB RAM',
    chipset: 'Exynos 7870 Octa',
    batteryMaH: '3000mAh',
    price: 'About 300 EUR'
  }, {
    name: 'Samsung Galaxy Tab S2 9.7',
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-tab-s2-97.jpg',
    size: '389g (Wi-Fi) / 392g (LTE), 5.6mm thickness',
    os: 'Android 5.0.2, up to 6.0.1 - T810…',
    storage: '32/64GB storage, microSD card slot',
    displaySize: '9.7"',
    cameraSize: '8MP',
    RAM: '3GB RAM',
    chipset: 'Exynos 5433',
    batteryMaH: '5870mAh',
    price: 'About 520 EUR'
  }, {
    name: 'Samsung Galaxy On8',
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-j7-2016.jpg',
    size: '169g, 7.8mm thickness',
    os: 'Android 6.0.1',
    storage: '16GB storage, microSD card slot',
    displaySize: '5.5"',
    cameraSize: '13MP',
    RAM: '3GB RAM',
    chipset: 'Exynos 7580 Octa',
    batteryMaH: '3300mAh',
    price: 'About 300 EUR'
  }, {
    name: 'Samsung Galaxy S7',
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s7--.jpg',
    size: '152g, 7.9mm thickness',
    os: 'Android 6.0, up to 7.0',
    storage: '32/64GB storage, microSD card slot',
    displaySize: '5.1"',
    cameraSize: '12MP',
    RAM: '4GB RAM',
    chipset: 'Exynos 8890 Octa',
    batteryMaH: '3000mAh',
    price: 'About 300 EUR'
  }, {
    name: 'Samsung Z3',
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-z3.jpg',
    size: '137g, 7.9mm thickness',
    os: 'Tizen 2.3, up to 2.4',
    storage: '8GB storage, microSD card slot',
    displaySize: '5.0"',
    cameraSize: '8MP',
    RAM: '1GB RAM',
    chipset: 'Spreadtrum SC7730',
    batteryMaH: '2600mAh',
    price: 'About 110 EUR'
  }, {
    name: 'Samsung Galaxy Xcover 3 G389F',
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-xcover-3-SM-G389F.jpg',
    size: '154g, 10mm thickness',
    os: 'Android 6.0',
    storage: '8GB storage, microSD card slot',
    displaySize: '4.5"',
    cameraSize: '5MP',
    RAM: '1.5GB RAM',
    chipset: 'Exynos 3475 Quad',
    batteryMaH: '2200mAh',
    price: 'About 300 EUR'
  }, {
    name: 'Samsung Galaxy A9 (2016)',
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a9-pro1.jpg',
    size: '200g, 7.4mm thickness',
    os: 'Android 5.1.1, up to 6.0.1',
    storage: '32GB storage, microSD card slot',
    displaySize: '6.0"',
    cameraSize: '13MP',
    RAM: '3GB RAM',
    chipset: 'Snapdragon 652',
    batteryMaH: '4000mAh',
    price: 'About 300 EUR'
  }, {
    name: 'Samsung Gear S3 classic',
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-gear-s3-classic.jpg',
    size: '59g, 12.9mm thickness',
    os: 'Tizen-based wearable platform 2.3.2',
    storage: '4GB storage, no card slot',
    displaySize: '1.3"',
    cameraSize: 'NO',
    RAM: '768MB RAM',
    chipset: 'Exynos 7270',
    batteryMaH: '380mAh',
    price: 'About 390 EUR'
  }, {
    name: 'Samsung Galaxy J7 (2016)',
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-j7-2016.jpg',
    size: '170g, 7.8mm thickness',
    os: 'Android 6.0.1',
    storage: '16GB storage, microSD card slot',
    displaySize: '5.5"',
    cameraSize: '13MP',
    RAM: '2GB RAM',
    chipset: 'Snapdragon 617',
    batteryMaH: '3300mAh',
    price: 'About 300 EUR'
  }, {
    name: 'Samsung Galaxy J Max',
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-j-max3.jpg',
    size: '289g, 8.7mm thickness',
    os: 'Android 5.1',
    storage: '8GB storage, microSD card slot',
    displaySize: '7.0"',
    cameraSize: '8MP',
    RAM: '1.5GB RAM',
    chipset: 'Spreadtrum SC8830',
    batteryMaH: '4000mAh',
    price: 'About 220 EUR'
  }, {
    name: 'Samsung Gear S2 3G',
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-gear-s2.jpg',
    size: '51g, 13.4mm thickness',
    os: 'Tizen-based wearable platform',
    storage: '4GB storage, no card slot',
    displaySize: '1.2"',
    cameraSize: 'NO',
    RAM: '512MB RAM',
    chipset: 'MSM8x26',
    batteryMaH: '300mAh',
    price: 'About 300 EUR'
  }, {
    name: 'Samsung Galaxy Note7',
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-note7.jpg',
    size: '169g, 7.9mm thickness',
    os: 'Android 6.0.1',
    storage: '64GB storage, microSD card slot',
    displaySize: '5.7"',
    cameraSize: '12MP',
    RAM: '4GB RAM',
    chipset: 'Exynos 8890 Octa',
    batteryMaH: '3500mAh',
    price: 'About 300 EUR'
  }, {
    name: 'Samsung Galaxy C5',
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-c5r3.jpg',
    size: '143g, 6.7mm thickness',
    os: 'Android 6.0.1',
    storage: '32/64GB storage, microSD card slot',
    displaySize: '5.2"',
    cameraSize: '16MP',
    RAM: '4GB RAM',
    chipset: 'Snapdragon 617',
    batteryMaH: '2600mAh',
    price: 'About 300 EUR'
  }, {
    name: 'Samsung Galaxy A5 (2017)',
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a5-2017-new.jpg',
    size: '157g, 7.9mm thickness',
    os: 'Android 6.0.1',
    storage: '32GB storage, microSD card slot',
    displaySize: '5.2"',
    cameraSize: '16MP',
    RAM: '3GB RAM',
    chipset: 'Exynos 7880 Octa',
    batteryMaH: '3000mAh',
    price: 'About 300 EUR'
  }, {
    name: 'Samsung Galaxy Tab A 7.0 (2016)',
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-tab-a-70-2016-.jpg',
    size: '283g, 8.7mm thickness',
    os: 'Android 5.1.1',
    storage: '8GB storage, microSD card slot',
    displaySize: '7.0"',
    cameraSize: '5MP',
    RAM: '1.5GB RAM',
    chipset: 'Snapdragon 410',
    batteryMaH: '4000mAh',
    price: 'About 130 EUR'
  }, {
    name: 'Samsung Galaxy J5 Prime',
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-j5-prime.jpg',
    size: '143g, 8.1mm thickness',
    os: 'Android 6.0.1',
    storage: '16/32GB storage, microSD card slot',
    displaySize: '5.0"',
    cameraSize: '13MP',
    RAM: '2GB RAM',
    chipset: 'Exynos 7570 Quad',
    batteryMaH: '2400mAh',
    price: 'About 230 EUR'
  }, {
    name: 'Samsung Galaxy On7 Pro',
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-on7-.jpg',
    size: '172g, 8mm thickness',
    os: 'Android 6.0.1',
    storage: '16GB storage, microSD card slot',
    displaySize: '5.5"',
    cameraSize: '13MP',
    RAM: '2GB RAM',
    chipset: 'Snapdragon 410',
    batteryMaH: '3000mAh',
    price: 'About 180 EUR'
  }, {
    name: 'Samsung Galaxy J3 Pro',
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-j3-2017r1.jpg',
    size: '139g, 8mm thickness',
    os: 'Android 5.1',
    storage: '16GB storage, microSD card slot',
    displaySize: '5.0"',
    cameraSize: '8MP',
    RAM: '2GB RAM',
    chipset: 'Snapdragon 410',
    batteryMaH: '2600mAh',
    price: 'About 150 EUR'
  }, {
    name: 'Samsung Galaxy View',
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-view.jpg',
    size: '2.65 kg, 11.9mm thickness',
    os: 'Android 5.1.1',
    storage: '32/64GB storage, microSD card slot',
    displaySize: '18.4"',
    cameraSize: '2.1MP',
    RAM: '2GB RAM',
    chipset: 'Exynos 7580 Octa',
    batteryMaH: '5700mAh',
    price: 'About 640 EUR'
  }, {
    name: 'Samsung Galaxy Tab E 8.0',
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-tab-e-80.jpg',
    size: '360g, 8.9mm thickness',
    os: 'Android 5.1.1, up to 6.0',
    storage: '16GB storage, microSD card slot',
    displaySize: '8.0"',
    cameraSize: '5MP',
    RAM: '1.5GB RAM',
    chipset: 'Snapdragon 410',
    batteryMaH: '5000mAh',
    price: 'About 180 EUR'
  }, {
    name: 'Samsung Gear S2 classic',
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-gear-s2-classic.jpg',
    size: '42g, 11.4mm thickness',
    os: 'Tizen-based wearable platform',
    storage: '4GB storage, no card slot',
    displaySize: '1.2"',
    cameraSize: 'NO',
    RAM: '512MB RAM',
    chipset: 'Exynos 3250 Dual',
    batteryMaH: '250mAh',
    price: 'About 270 EUR'
  }, {
    name: 'Samsung Galaxy Express Prime',
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-express-prime.jpg',
    size: '138.9g, 7.9mm thickness',
    os: 'Android 6.0',
    storage: '16GB 1.5GB RAM storage, microSD card slot',
    displaySize: '5.0"',
    cameraSize: '5MP',
    RAM: '1.5GB RAM',
    chipset: 'Exynos 3475 Quad',
    batteryMaH: '2600mAh',
    price: 'About 110 EUR'
  }, {
    name: 'Samsung Galaxy S7 active',
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s7-active.jpg',
    size: '184.8g, 9.9mm thickness',
    os: 'Android 6.0, up to 7.0',
    storage: '32GB storage, microSD card slot',
    displaySize: '5.1"',
    cameraSize: '12MP',
    RAM: '4GB RAM',
    chipset: 'Snapdragon 820',
    batteryMaH: '4000mAh',
    price: 'About 300 EUR'
  }, {
    name: 'Samsung Galaxy S6 edge+',
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s6-edge-plus.jpg',
    size: '153g, 6.9mm thickness',
    os: 'Android 5.1.1, up to 7.0',
    storage: '32/64GB storage, no card slot',
    displaySize: '5.7"',
    cameraSize: '16MP',
    RAM: '4GB RAM',
    chipset: 'Exynos 7420 Octa',
    batteryMaH: '3000mAh',
    price: 'About 300 EUR'
  }, {
    name: 'Samsung Galaxy J7 Max',
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-j7-max.jpg',
    size: '179g, 8.1mm thickness',
    os: 'Android 7.0',
    storage: '32GB storage, microSD card slot',
    displaySize: '5.7"',
    cameraSize: '13MP',
    RAM: '4GB RAM',
    chipset: 'MT6757 Helio P20',
    batteryMaH: '3300mAh',
    price: 'About 250 EUR'
  }, {
    name: 'Samsung Galaxy S6 edge+ (USA)',
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s6-edge-plus.jpg',
    size: '153g, 6.9mm thickness',
    os: 'Android 5.1.1',
    storage: '32/64GB storage, no card slot',
    displaySize: '5.7"',
    cameraSize: '16MP',
    RAM: '4GB RAM',
    chipset: 'Exynos 7420 Octa',
    batteryMaH: '3000mAh',
    price: 'About 550 EUR'
  }, {
    name: 'Samsung Galaxy J7 V',
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-j7-v-2017.jpg',
    size: '167.3g, 8.6mm thickness',
    os: 'Android 7.0.1',
    storage: '16GB storage, microSD card slot',
    displaySize: '5.5"',
    cameraSize: '8MP',
    RAM: '2GB RAM',
    chipset: 'Snapdragon 625',
    batteryMaH: '3300mAh',
    price: 'About 240 USD'
  }, {
    name: 'Samsung Galaxy J3 Emerge',
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-j3-emerge-.jpg',
    size: '147g, 8.7mm thickness',
    os: 'Android 6.0.1Android 7.0 - Am…',
    storage: '16GB storage, microSD card slot',
    displaySize: '5.0"',
    cameraSize: '5MP',
    RAM: '1.5GB RAM',
    chipset: 'Snapdragon 430',
    batteryMaH: '2600mAh',
    price: 'About 235 USD'
  }, {
    name: 'Samsung Galaxy A8 (2016)',
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a8-2016r1-.jpg',
    size: '182g, 7.2mm thickness',
    os: 'Android 6.0.1',
    storage: '32GB storage, microSD card slot',
    displaySize: '5.7"',
    cameraSize: '16MP',
    RAM: '3GB RAM',
    chipset: 'Exynos 7420 Octa',
    batteryMaH: '3300mAh',
    price: 'About 560 EUR'
  }, {
    name: 'Samsung Galaxy On7 (2016)',
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-on7-2016-g6100-c.jpg',
    size: '167g, 8mm thickness',
    os: 'Android 6.0.1',
    storage: '32GB storage, microSD card slot',
    displaySize: '5.5"',
    cameraSize: '13MP',
    RAM: '3GB RAM',
    chipset: 'Snapdragon 625',
    batteryMaH: '3300mAh',
    price: 'About 260 EUR'
  }, {
    name: 'Samsung Galaxy S6 edge+ Duos',
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s6-edge-plus.jpg',
    size: '153g, 6.9mm thickness',
    os: 'Android 5.1.1, up to 6.0.1',
    storage: '32/64GB storage, no card slot',
    displaySize: '5.7"',
    cameraSize: '16MP',
    RAM: '4GB RAM',
    chipset: 'Exynos 7420 Octa',
    batteryMaH: '3000mAh',
    price: 'About 530 EUR'
  }, {
    name: 'Samsung Galaxy Xcover 4',
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-xcover4-g390f-.jpg',
    size: '172g, 9.7mm thickness',
    os: 'Android 7.0',
    storage: '16GB storage, microSD card slot',
    displaySize: '5.0"',
    cameraSize: '13MP',
    RAM: '2GB RAM',
    chipset: 'Exynos 7570 Quad',
    batteryMaH: '2800mAh',
    price: 'About 240 EUR'
  }, {
    name: 'Samsung Galaxy Grand Prime Plus',
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-j2-prime-2016.jpg',
    size: '160g, 8.9mm thickness',
    os: 'Android 6.0',
    storage: '8GB storage, microSD card slot',
    displaySize: '5.0"',
    cameraSize: '8MP',
    RAM: '1.5GB RAM',
    chipset: 'MT6737T',
    batteryMaH: '2600mAh',
    price: 'About 140 EUR'
  }, {
    name: 'Samsung Galaxy S5 Neo',
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s5-neo.jpg',
    size: '145g, 8.1mm thickness',
    os: 'Android 5.1.1, up to 6.0.1',
    storage: '16GB storage, microSD card slot',
    displaySize: '5.1"',
    cameraSize: '16MP',
    RAM: '2GB RAM',
    chipset: 'Exynos 7580 Octa',
    batteryMaH: '2800mAh',
    price: 'About 350 EUR'
  }, {
    name: 'Samsung Galaxy C7',
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-c7.jpg',
    size: '169g, 6.8mm thickness',
    os: 'Android 6.0.1',
    storage: '32/64GB storage, microSD card slot',
    displaySize: '5.7"',
    cameraSize: '16MP',
    RAM: '4GB RAM',
    chipset: 'Snapdragon 625',
    batteryMaH: '3300mAh',
    price: 'About 300 EUR'
  }, {
    name: 'Samsung Galaxy A3 (2016)',
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a3-2016.jpg',
    size: '132g, 7.3mm thickness',
    os: 'Android 5.1.1, up to 7.0',
    storage: '16GB storage, microSD card slot',
    displaySize: '4.7"',
    cameraSize: '13MP',
    RAM: '1.5GB RAM',
    chipset: 'Exynos 7578',
    batteryMaH: '2300mAh',
    price: 'About 200 EUR'
  }, {
    name: 'Samsung Galaxy C5 Pro',
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-c5-pro-sm-c5010.jpg',
    size: '145g, 7mm thickness',
    os: 'Android 7.0',
    storage: '64GB storage, microSD card slot',
    displaySize: '5.2"',
    cameraSize: '16MP',
    RAM: '4GB RAM',
    chipset: 'Snapdragon 626',
    batteryMaH: '2600mAh',
    price: 'About 300 EUR'
  }, {
    name: 'Samsung Galaxy Note5',
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-note5.jpg',
    size: '171g, 7.6mm thickness',
    os: 'Android 5.1.1, up to 7.0',
    storage: '32/64/128GB storage, no card slot',
    displaySize: '5.7"',
    cameraSize: '16MP',
    RAM: '4GB RAM',
    chipset: 'Exynos 7420 Octa',
    batteryMaH: '3000mAh',
    price: 'About 300 EUR'
  }, {
    name: 'Samsung Gear S2 classic 3G',
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-gear-s2-classic-3g.jpg',
    size: '54g, 13.4mm thickness',
    os: 'Tizen-based wearable platform',
    storage: '4GB storage, no card slot',
    displaySize: '1.2"',
    cameraSize: 'NO',
    RAM: '512MB RAM',
    chipset: 'Exynos 3250 Dual',
    batteryMaH: '300mAh',
    price: 'About 350 EUR'
  }, {
    name: 'Samsung Gear S2',
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-gear-s2.jpg',
    size: '47g, 11.4mm thickness',
    os: 'Tizen-based wearable platform',
    storage: '4GB storage, no card slot',
    displaySize: '1.2"',
    cameraSize: 'NO',
    RAM: '512MB RAM',
    chipset: 'Exynos 3250 Dual',
    batteryMaH: '250mAh',
    price: 'About 220 EUR'
  }, {
    name: 'Samsung Galaxy C9 Pro',
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-c9-pro-.jpg',
    size: '189g, 6.9mm thickness',
    os: 'Android 6.0.1',
    storage: '64GB storage, microSD card slot',
    displaySize: '6.0"',
    cameraSize: '16MP',
    RAM: '6GB RAM',
    chipset: 'Snapdragon 653',
    batteryMaH: '4000mAh',
    price: 'About 620 EUR'
  }, {
    name: 'Samsung Galaxy J1 mini prime',
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-j1-nxt.jpg',
    size: '126g, 10.8mm thickness',
    os: 'Android 5.1 - 3G modelAndroid…',
    storage: '8GB storage, microSD card slot',
    displaySize: '4.0"',
    cameraSize: '5MP',
    RAM: '1GB RAM',
    chipset: 'Spreadtrum SC9830',
    batteryMaH: '1500mAh',
    price: 'About 110 EUR'
  }, {
    name: 'Samsung Galaxy A3 (2017)',
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a3-2017.jpg',
    size: '138g, 7.9mm thickness',
    os: 'Android 6.0.1, up to 7.0',
    storage: '16GB storage, microSD card slot',
    displaySize: '4.7"',
    cameraSize: '13MP',
    RAM: '2GB RAM',
    chipset: 'Exynos 7870 Octa',
    batteryMaH: '2350mAh',
    price: 'About 300 EUR'
  }, {
    name: 'Samsung Gear S3 frontier LTE',
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-gear-s3-frontier-lte.jpg',
    size: '63g, 12.9mm thickness',
    os: 'Tizen-based wearable platform 2.3.2',
    storage: '4GB storage, no card slot',
    displaySize: '1.3"',
    cameraSize: 'NO',
    RAM: '768MB RAM',
    chipset: 'Exynos 7270',
    batteryMaH: '380mAh',
    price: 'About 450 EUR'
  }, {
    name: 'Samsung Galaxy A5 (2016)',
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-a5-2016.jpg',
    size: '155g, 7.3mm thickness',
    os: 'Android 5.1.1, up to 7.0',
    storage: '16GB storage, microSD card slot',
    displaySize: '5.2"',
    cameraSize: '13MP',
    RAM: '2GB RAM',
    chipset: 'Exynos 7580 Octa',
    batteryMaH: '2900mAh',
    price: 'About 300 EUR'
  }, {
    name: 'Samsung Galaxy J2 (2016)',
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-j2-2016-new.jpg',
    size: '138g, 8mm thickness',
    os: 'Android 6.0.1',
    storage: '8GB storage, microSD card slot',
    displaySize: '5.0"',
    cameraSize: '8MP',
    RAM: '1.5GB RAM',
    chipset: 'Spreadtrum SC8830',
    batteryMaH: '2600mAh',
    price: 'About 300 EUR'
  }, {
    name: 'Samsung Galaxy J7 (2017)',
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-j7-2017-sm-j730f.jpg',
    size: '181g, 8mm thickness',
    os: 'Android 7.0',
    storage: '16GB storage, microSD card slot',
    displaySize: '5.5"',
    cameraSize: '13MP',
    RAM: '3GB RAM',
    chipset: 'Exynos 7870 Octa',
    batteryMaH: '3600mAh',
    price: 'About 300 EUR'
  }, {
    name: 'Samsung Galaxy J2 Pro (2016)',
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-j2-2016-new.jpg',
    size: '138g, 8mm thickness',
    os: 'Android 6.0.1',
    storage: '16GB storage, microSD card slot',
    displaySize: '5.0"',
    cameraSize: '8MP',
    RAM: '2GB RAM',
    chipset: 'Spreadtrum SC8830',
    batteryMaH: '2600mAh',
    price: 'About 160 EUR'
  }, {
    name: 'Samsung Galaxy Folder',
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-folder-SM-G150.jpg',
    size: '155g, 15.3mm thickness',
    os: 'Android 5.1',
    storage: '8GB storage, microSD card slot',
    displaySize: '3.8"',
    cameraSize: '8MP',
    RAM: '1.5GB RAM',
    chipset: '',
    batteryMaH: '1800mAh',
    price: 'About 260 EUR'
  }, {
    name: 'Samsung Galaxy S7 (USA)',
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s7-usa.jpg',
    size: '152g, 7.9mm thickness',
    os: 'Android 6.0, up to 7.0',
    storage: '32GB storage, microSD card slot',
    displaySize: '5.1"',
    cameraSize: '12MP',
    RAM: '4GB RAM',
    chipset: 'Snapdragon 820',
    batteryMaH: '3000mAh',
    price: 'About 450 EUR'
  }, {
    name: 'Samsung Galaxy S7 edge',
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s7-edge-.jpg',
    size: '157g, 7.7mm thickness',
    os: 'Android 6.0, up to 7.0',
    storage: '32/64/128GB storage, microSD card slot',
    displaySize: '5.5"',
    cameraSize: '12MP',
    RAM: '4GB RAM',
    chipset: 'Snapdragon 820',
    batteryMaH: '3600mAh',
    price: 'About 300 EUR'
  }, {
    name: 'Samsung Galaxy J3 (2016)',
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-j3.jpg',
    size: '138g, 7.9mm thickness',
    os: 'Android 5.1.1 or Android 6.0',
    storage: '8/16GB storage, microSD card slot',
    displaySize: '5.0"',
    cameraSize: '8MP',
    RAM: '2GB RAM',
    chipset: 'Spreadtrum SC9830',
    batteryMaH: '2600mAh',
    price: 'About 300 EUR'
  }, {
    name: 'Samsung Galaxy S8+',
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s8-plus-.jpg',
    size: '173g, 8.1mm thickness',
    os: 'Android 7.0',
    storage: '64GB storage, microSD card slot',
    displaySize: '6.2"',
    cameraSize: '12MP',
    RAM: '6GB RAM',
    chipset: 'Exynos 8895 Octa',
    batteryMaH: '3500mAh',
    price: 'About 300 EUR'
  }, {
    name: 'Samsung Galaxy S8',
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s8-.jpg',
    size: '155g, 8mm thickness',
    os: 'Android 7.0',
    storage: '64GB storage, microSD card slot',
    displaySize: '5.8"',
    cameraSize: '12MP',
    RAM: '4GB RAM',
    chipset: 'Exynos 8895 Octa',
    batteryMaH: '3000mAh',
    price: 'About 300 EUR'
  }, {
    name: 'Samsung Galaxy S8 Active',
    image: 'http://cdn2.gsmarena.com/vv/bigpic/samsung-galaxy-s8-active.jpg',
    size: '208.1g, 9.9mm thickness',
    os: 'Android 7.0',
    storage: '64GB storage, microSD card slot',
    displaySize: '5.8"',
    cameraSize: '12MP',
    RAM: '4GB RAM',
    chipset: 'Snapdragon 835',
    batteryMaH: '4000mAh',
    price: 'About 850 USD'
  },
  ];

  getAll() { return this.items; }
}

